apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-02-14T09:32:20Z"
    name: default
    namespace: delivery
    resourceVersion: "2316776"
    uid: 3e98ccc0-86f6-4188-95b4-850ce61bf40f
kind: List
metadata:
  resourceVersion: ""
