apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: IngressClass
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: kong:networking.k8s.io/IngressClass:kong/kong
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"IngressClass","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"kong:networking.k8s.io/IngressClass:kong/kong","meta.helm.sh/release-name":"kong","meta.helm.sh/release-namespace":"kong"},"creationTimestamp":"2026-02-10T18:15:42Z","generation":1,"labels":{"app.kubernetes.io/instance":"kong","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"kong","app.kubernetes.io/version":"3.13","helm.sh/chart":"kong-3.0.2"},"name":"kong","resourceVersion":"7190606","uid":"93417403-07c8-47fc-8f6e-0285aa4c020f"},"spec":{"controller":"ingress-controllers.konghq.com/kong"}}
      meta.helm.sh/release-name: kong
      meta.helm.sh/release-namespace: kong
    creationTimestamp: "2026-03-14T13:24:03Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: kong
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kong
      app.kubernetes.io/version: "3.13"
      helm.sh/chart: kong-3.0.2
    name: kong
    resourceVersion: "10273101"
    uid: 8574aba7-e2aa-4916-b374-fcd569be88cb
  spec:
    controller: ingress-controllers.konghq.com/kong
- apiVersion: networking.k8s.io/v1
  kind: IngressClass
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: kong:networking.k8s.io/IngressClass:kong/nginx
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"IngressClass","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"kong:networking.k8s.io/IngressClass:kong/nginx"},"creationTimestamp":"2026-02-03T15:52:54Z","generation":1,"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx","app.kubernetes.io/part-of":"ingress-nginx","app.kubernetes.io/version":"1.11.3"},"name":"nginx","resourceVersion":"1354074","uid":"aa567430-c6df-4ff3-b27f-b200047b8d6b"},"spec":{"controller":"k8s.io/ingress-nginx"}}
    creationTimestamp: "2026-03-14T13:24:03Z"
    generation: 1
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.11.3
    name: nginx
    resourceVersion: "10273100"
    uid: 7df28d3c-c5f8-4b35-ae36-1d7fc0a183b3
  spec:
    controller: k8s.io/ingress-nginx
kind: List
metadata:
  resourceVersion: ""
