apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-02-12T14:00:57Z"
    name: default
    namespace: kafka
    resourceVersion: "1803541"
    uid: ba33193c-ae5e-4397-8f53-4b253b7545f4
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-02-12T14:33:57Z"
    labels:
      app.kubernetes.io/instance: my-kafka
      app.kubernetes.io/managed-by: strimzi-cluster-operator
      app.kubernetes.io/name: entity-operator
      app.kubernetes.io/part-of: strimzi-my-kafka
      strimzi.io/cluster: my-kafka
      strimzi.io/component-type: entity-operator
      strimzi.io/kind: Kafka
      strimzi.io/name: my-kafka-entity-operator
    name: my-kafka-entity-operator
    namespace: kafka
    ownerReferences:
    - apiVersion: kafka.strimzi.io/v1beta2
      blockOwnerDeletion: true
      controller: false
      kind: Kafka
      name: my-kafka
      uid: 2f4ace1b-eded-4ed3-8750-f4a99bb1cbad
    resourceVersion: "1809549"
    uid: 0fecf990-fd8d-4d4d-b45e-5ded0f5fcad8
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-02-12T14:32:50Z"
    labels:
      app.kubernetes.io/instance: my-kafka
      app.kubernetes.io/managed-by: strimzi-cluster-operator
      app.kubernetes.io/name: kafka
      app.kubernetes.io/part-of: strimzi-my-kafka
      strimzi.io/cluster: my-kafka
      strimzi.io/component-type: kafka
      strimzi.io/kind: Kafka
      strimzi.io/name: my-kafka-kafka
    name: my-kafka-kafka
    namespace: kafka
    ownerReferences:
    - apiVersion: kafka.strimzi.io/v1beta2
      blockOwnerDeletion: true
      controller: false
      kind: Kafka
      name: my-kafka
      uid: 2f4ace1b-eded-4ed3-8750-f4a99bb1cbad
    resourceVersion: "1809022"
    uid: 06e2816e-743d-4be6-b907-a16f0c8a999c
kind: List
metadata:
  resourceVersion: ""
