apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-02-09T12:10:06Z"
    name: default
    namespace: echo
    resourceVersion: "1346787"
    uid: 692423b6-20ef-45d9-9a2c-8977debc227d
kind: List
metadata:
  resourceVersion: ""
