apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: orders:apps/Deployment:orders/spce-orders
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"orders:apps/Deployment:orders/spce-orders","deployment.kubernetes.io/revision":"24"},"creationTimestamp":"2026-02-13T13:19:58Z","generation":26,"name":"spce-orders","namespace":"orders","resourceVersion":"5827821","uid":"3d14f01b-7aeb-48eb-a3ec-e57487a98ade"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"spce-orders"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"cattle.io/timestamp":"2026-02-15T20:20:13Z","kubectl.kubernetes.io/restartedAt":"2026-02-15T21:16:39+01:00","vault.hashicorp.com/agent-inject":"true","vault.hashicorp.com/agent-inject-secret-appsettings.Production.json":"kv/data/orders-shipments/spce-orders/production","vault.hashicorp.com/agent-inject-secret-appsettings.json":"kv/data/orders-shipments/spce-orders/production","vault.hashicorp.com/agent-inject-secret-config.env":"kv/data/orders-shipments/spce-orders/production","vault.hashicorp.com/agent-inject-template-appsettings.Production.json":"{{- with secret \"kv/data/orders-shipments/spce-orders/production\" -}}\n{\n  \"Service\": { \"Name\": \"{{ .Data.data.Service__Name }}\" },\n  \"Kafka\": {\n    \"BootstrapServers\": \"{{ .Data.data.Kafka__BootstrapServers }}\",\n    \"ShipmentRequestsTopic\": \"{{ .Data.data.Kafka__ShipmentRequestsTopic }}\"\n  },\n  \"Swagger\": { \"Enabled\": {{ .Data.data.Swagger__Enabled }} },\n  \"Logging\": {\n    \"LogLevel\": {\n      \"Default\": \"{{ .Data.data.Logging__LogLevel__Default }}\",\n      \"Microsoft.AspNetCore\": \"{{ .Data.data.Logging__LogLevel__Microsoft_AspNetCore }}\"\n    }\n  }\n}\n{{- end }}","vault.hashicorp.com/agent-inject-template-appsettings.json":"{{- with secret \"kv/data/orders-shipments/spce-orders/production\" -}}\n{\n  \"Service\": { \"Name\": \"{{ .Data.data.Service__Name }}\" },\n  \"Kafka\": {\n    \"BootstrapServers\": \"{{ .Data.data.Kafka__BootstrapServers }}\",\n    \"ShipmentRequestsTopic\": \"{{ .Data.data.Kafka__ShipmentRequestsTopic }}\"\n  },\n  \"Swagger\": { \"Enabled\": {{ .Data.data.Swagger__Enabled }} },\n  \"Logging\": {\n    \"LogLevel\": {\n      \"Default\": \"{{ .Data.data.Logging__LogLevel__Default }}\",\n      \"Microsoft.AspNetCore\": \"{{ .Data.data.Logging__LogLevel__Microsoft_AspNetCore }}\"\n    }\n  }\n}\n{{- end }}","vault.hashicorp.com/agent-inject-template-config.env":"{{- with secret \"kv/data/orders-shipments/spce-orders/production\" -}}\nexport Service__Name=\"{{ .Data.data.Service__Name }}\"\nexport Kafka__BootstrapServers=\"{{ .Data.data.Kafka__BootstrapServers }}\"\nexport Kafka__ShipmentRequestsTopic=\"{{ .Data.data.Kafka__ShipmentRequestsTopic }}\"\nexport Swagger__Enabled=\"{{ .Data.data.Swagger__Enabled }}\"\nexport Logging__LogLevel__Default=\"{{ .Data.data.Logging__LogLevel__Default }}\"\nexport Logging__LogLevel__Microsoft_AspNetCore=\"{{ .Data.data.Logging__LogLevel__Microsoft_AspNetCore }}\"\n{{- end }}","vault.hashicorp.com/agent-service-account-token-volume-name":"vault-k8s-token","vault.hashicorp.com/role":"orders-spce-orders-production","vault.hashicorp.com/vault-addr":"http://vault.vault.svc.cluster.local:8200"},"labels":{"app":"spce-orders"}},"spec":{"containers":[{"args":["cp /vault/secrets/appsettings.json /app/appsettings.json \u0026\u0026 exec dotnet spce-orders.dll"],"command":["/bin/sh","-lc"],"env":[{"name":"SERVICE_NAME","value":"spce-orders"},{"name":"KAFKA_BOOTSTRAP_SERVERS","value":"my-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"},{"name":"KAFKA_TOPIC_SHIPMENT_REQUESTS","value":"shipment-requests"}],"image":"abu7midan/spce-orders:1.0","imagePullPolicy":"IfNotPresent","name":"spce-orders","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"spce-orders","serviceAccountName":"spce-orders","terminationGracePeriodSeconds":30,"volumes":[{"name":"vault-k8s-token","projected":{"defaultMode":420,"sources":[{"serviceAccountToken":{"audience":"vault","expirationSeconds":3600,"path":"token"}}]}}]}}},"status":{"conditions":[{"lastTransitionTime":"2026-02-15T19:51:50Z","lastUpdateTime":"2026-02-15T20:20:29Z","message":"ReplicaSet \"spce-orders-6c9df9fd99\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2026-02-26T00:34:15Z","lastUpdateTime":"2026-02-26T00:34:15Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"}],"observedGeneration":26,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
  creationTimestamp: "2026-02-27T08:04:47Z"
  generation: 1
  name: spce-orders
  namespace: orders
  resourceVersion: "6192766"
  uid: bb6a89e0-1262-4cc8-a6b8-14e2a3e8a48a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spce-orders
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2026-02-15T20:20:13Z"
        kubectl.kubernetes.io/restartedAt: "2026-02-15T21:16:39+01:00"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-appsettings.Production.json: kv/data/orders-shipments/spce-orders/production
        vault.hashicorp.com/agent-inject-secret-appsettings.json: kv/data/orders-shipments/spce-orders/production
        vault.hashicorp.com/agent-inject-secret-config.env: kv/data/orders-shipments/spce-orders/production
        vault.hashicorp.com/agent-inject-template-appsettings.Production.json: |-
          {{- with secret "kv/data/orders-shipments/spce-orders/production" -}}
          {
            "Service": { "Name": "{{ .Data.data.Service__Name }}" },
            "Kafka": {
              "BootstrapServers": "{{ .Data.data.Kafka__BootstrapServers }}",
              "ShipmentRequestsTopic": "{{ .Data.data.Kafka__ShipmentRequestsTopic }}"
            },
            "Swagger": { "Enabled": {{ .Data.data.Swagger__Enabled }} },
            "Logging": {
              "LogLevel": {
                "Default": "{{ .Data.data.Logging__LogLevel__Default }}",
                "Microsoft.AspNetCore": "{{ .Data.data.Logging__LogLevel__Microsoft_AspNetCore }}"
              }
            }
          }
          {{- end }}
        vault.hashicorp.com/agent-inject-template-appsettings.json: |-
          {{- with secret "kv/data/orders-shipments/spce-orders/production" -}}
          {
            "Service": { "Name": "{{ .Data.data.Service__Name }}" },
            "Kafka": {
              "BootstrapServers": "{{ .Data.data.Kafka__BootstrapServers }}",
              "ShipmentRequestsTopic": "{{ .Data.data.Kafka__ShipmentRequestsTopic }}"
            },
            "Swagger": { "Enabled": {{ .Data.data.Swagger__Enabled }} },
            "Logging": {
              "LogLevel": {
                "Default": "{{ .Data.data.Logging__LogLevel__Default }}",
                "Microsoft.AspNetCore": "{{ .Data.data.Logging__LogLevel__Microsoft_AspNetCore }}"
              }
            }
          }
          {{- end }}
        vault.hashicorp.com/agent-inject-template-config.env: |-
          {{- with secret "kv/data/orders-shipments/spce-orders/production" -}}
          export Service__Name="{{ .Data.data.Service__Name }}"
          export Kafka__BootstrapServers="{{ .Data.data.Kafka__BootstrapServers }}"
          export Kafka__ShipmentRequestsTopic="{{ .Data.data.Kafka__ShipmentRequestsTopic }}"
          export Swagger__Enabled="{{ .Data.data.Swagger__Enabled }}"
          export Logging__LogLevel__Default="{{ .Data.data.Logging__LogLevel__Default }}"
          export Logging__LogLevel__Microsoft_AspNetCore="{{ .Data.data.Logging__LogLevel__Microsoft_AspNetCore }}"
          {{- end }}
        vault.hashicorp.com/agent-service-account-token-volume-name: vault-k8s-token
        vault.hashicorp.com/role: orders-spce-orders-production
        vault.hashicorp.com/vault-addr: http://vault.vault.svc.cluster.local:8200
      labels:
        app: spce-orders
    spec:
      containers:
        - args:
            - cp /vault/secrets/appsettings.json /app/appsettings.json && exec dotnet spce-orders.dll
          command:
            - /bin/sh
            - -lc
          env:
            - name: SERVICE_NAME
              value: spce-orders
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: KAFKA_TOPIC_SHIPMENT_REQUESTS
              value: shipment-requests
          image: abu7midan/spce-orders:1.0
          imagePullPolicy: IfNotPresent
          name: spce-orders
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: spce-orders
      serviceAccountName: spce-orders
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vault-k8s-token
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  audience: vault
                  expirationSeconds: 3600
                  path: token
status:
  conditions:
    - lastTransitionTime: "2026-02-27T08:04:47Z"
      lastUpdateTime: "2026-02-27T08:04:47Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2026-02-27T08:14:48Z"
      lastUpdateTime: "2026-02-27T08:14:48Z"
      message: ReplicaSet "spce-orders-bdd7f5b76" has timed out progressing.
      reason: ProgressDeadlineExceeded
      status: "False"
      type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
