apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: observability:apps/Deployment:observability/kibana-kb
      deployment.kubernetes.io/revision: "4"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"observability:apps/Deployment:observability/kibana-kb","deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2026-02-13T19:05:44Z","generation":2,"labels":{"common.k8s.elastic.co/template-hash":"55752753","common.k8s.elastic.co/type":"kibana","kibana.k8s.elastic.co/name":"kibana"},"name":"kibana-kb","namespace":"observability","ownerReferences":[{"apiVersion":"kibana.k8s.elastic.co/v1","blockOwnerDeletion":true,"controller":true,"kind":"Kibana","name":"kibana","uid":"d9c229d7-eed3-45bb-af4d-4743c08948ed"}],"resourceVersion":"5771261","uid":"a8faa851-6b73-4725-b22a-b97526d60ba3"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"common.k8s.elastic.co/type":"kibana","kibana.k8s.elastic.co/name":"kibana"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"co.elastic.logs/module":"kibana","kibana.k8s.elastic.co/config-hash":"4270124593"},"labels":{"common.k8s.elastic.co/type":"kibana","kibana.k8s.elastic.co/name":"kibana","kibana.k8s.elastic.co/version":"9.3.0"}},"spec":{"automountServiceAccountToken":false,"containers":[{"image":"docker.elastic.co/kibana/kibana:9.3.0","imagePullPolicy":"IfNotPresent","name":"kibana","ports":[{"containerPort":5601,"name":"https","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/login","port":5601,"scheme":"HTTPS"},"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"resources":{"limits":{"memory":"1Gi"},"requests":{"memory":"1Gi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":true,"runAsGroup":1000,"runAsUser":1000},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/mnt/elastic-internal/http-certs","name":"elastic-internal-http-certificates","readOnly":true},{"mountPath":"/mnt/elastic-internal/kibana-config","name":"elastic-internal-kibana-config","readOnly":true},{"mountPath":"/usr/share/kibana/config","name":"elastic-internal-kibana-config-local"},{"mountPath":"/usr/share/kibana/config/elasticsearch-certs","name":"elasticsearch-certs","readOnly":true},{"mountPath":"/usr/share/kibana/data","name":"kibana-data"},{"mountPath":"/usr/share/kibana/logs","name":"kibana-logs"},{"mountPath":"/usr/share/kibana/plugins","name":"kibana-plugins"},{"mountPath":"/mnt/elastic-internal/scripts","name":"kibana-scripts","readOnly":true},{"mountPath":"/tmp","name":"temp-volume"}]}],"dnsPolicy":"ClusterFirst","initContainers":[{"command":["/usr/bin/env","bash","-c","/mnt/elastic-internal/scripts/init.sh"],"env":[{"name":"POD_IP","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"status.podIP"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"NODE_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"spec.nodeName"}}},{"name":"NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}}],"image":"docker.elastic.co/kibana/kibana:9.3.0","imagePullPolicy":"IfNotPresent","name":"elastic-internal-init","resources":{"limits":{"cpu":"100m","memory":"50Mi"},"requests":{"cpu":"100m","memory":"50Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/mnt/elastic-internal/http-certs","name":"elastic-internal-http-certificates","readOnly":true},{"mountPath":"/mnt/elastic-internal/kibana-config","name":"elastic-internal-kibana-config","readOnly":true},{"mountPath":"/mnt/elastic-internal/kibana-config-local","name":"elastic-internal-kibana-config-local"},{"mountPath":"/usr/share/kibana/config/elasticsearch-certs","name":"elasticsearch-certs","readOnly":true},{"mountPath":"/usr/share/kibana/data","name":"kibana-data"},{"mountPath":"/usr/share/kibana/logs","name":"kibana-logs"},{"mountPath":"/mnt/elastic-internal/kibana-plugins-local","name":"kibana-plugins"},{"mountPath":"/mnt/elastic-internal/scripts","name":"kibana-scripts","readOnly":true},{"mountPath":"/tmp","name":"temp-volume"}]}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":1000},"terminationGracePeriodSeconds":30,"volumes":[{"name":"elastic-internal-http-certificates","secret":{"defaultMode":420,"optional":false,"secretName":"kibana-kb-http-certs-internal"}},{"name":"elastic-internal-kibana-config","secret":{"defaultMode":420,"optional":false,"secretName":"kibana-kb-config"}},{"emptyDir":{},"name":"elastic-internal-kibana-config-local"},{"name":"elasticsearch-certs","secret":{"defaultMode":420,"optional":false,"secretName":"kibana-kb-es-ca"}},{"emptyDir":{},"name":"kibana-data"},{"emptyDir":{},"name":"kibana-logs"},{"emptyDir":{},"name":"kibana-plugins"},{"configMap":{"defaultMode":493,"name":"kibana-kb-scripts","optional":false},"name":"kibana-scripts"},{"emptyDir":{},"name":"temp-volume"}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2026-02-13T19:05:45Z","lastUpdateTime":"2026-02-13T19:29:25Z","message":"ReplicaSet \"kibana-kb-558fcc5bdc\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2026-02-25T23:46:16Z","lastUpdateTime":"2026-02-25T23:46:16Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":2,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    creationTimestamp: "2026-02-13T19:05:44Z"
    generation: 5
    labels:
      common.k8s.elastic.co/template-hash: "55752753"
      common.k8s.elastic.co/type: kibana
      kibana.k8s.elastic.co/name: kibana
    name: kibana-kb
    namespace: observability
    ownerReferences:
    - apiVersion: kibana.k8s.elastic.co/v1
      blockOwnerDeletion: true
      controller: true
      kind: Kibana
      name: kibana
      uid: d9c229d7-eed3-45bb-af4d-4743c08948ed
    resourceVersion: "6201935"
    uid: a8faa851-6b73-4725-b22a-b97526d60ba3
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        common.k8s.elastic.co/type: kibana
        kibana.k8s.elastic.co/name: kibana
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          co.elastic.logs/module: kibana
          kibana.k8s.elastic.co/config-hash: "4270124593"
        labels:
          common.k8s.elastic.co/type: kibana
          kibana.k8s.elastic.co/name: kibana
          kibana.k8s.elastic.co/version: 9.3.0
      spec:
        automountServiceAccountToken: false
        containers:
        - image: docker.elastic.co/kibana/kibana:9.3.0
          imagePullPolicy: IfNotPresent
          name: kibana
          ports:
          - containerPort: 5601
            name: https
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 5601
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsUser: 1000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /mnt/elastic-internal/http-certs
            name: elastic-internal-http-certificates
            readOnly: true
          - mountPath: /mnt/elastic-internal/kibana-config
            name: elastic-internal-kibana-config
            readOnly: true
          - mountPath: /usr/share/kibana/config
            name: elastic-internal-kibana-config-local
          - mountPath: /usr/share/kibana/config/elasticsearch-certs
            name: elasticsearch-certs
            readOnly: true
          - mountPath: /usr/share/kibana/data
            name: kibana-data
          - mountPath: /usr/share/kibana/logs
            name: kibana-logs
          - mountPath: /usr/share/kibana/plugins
            name: kibana-plugins
          - mountPath: /mnt/elastic-internal/scripts
            name: kibana-scripts
            readOnly: true
          - mountPath: /tmp
            name: temp-volume
        dnsPolicy: ClusterFirst
        initContainers:
        - command:
          - /usr/bin/env
          - bash
          - -c
          - /mnt/elastic-internal/scripts/init.sh
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          image: docker.elastic.co/kibana/kibana:9.3.0
          imagePullPolicy: IfNotPresent
          name: elastic-internal-init
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /mnt/elastic-internal/http-certs
            name: elastic-internal-http-certificates
            readOnly: true
          - mountPath: /mnt/elastic-internal/kibana-config
            name: elastic-internal-kibana-config
            readOnly: true
          - mountPath: /mnt/elastic-internal/kibana-config-local
            name: elastic-internal-kibana-config-local
          - mountPath: /usr/share/kibana/config/elasticsearch-certs
            name: elasticsearch-certs
            readOnly: true
          - mountPath: /usr/share/kibana/data
            name: kibana-data
          - mountPath: /usr/share/kibana/logs
            name: kibana-logs
          - mountPath: /mnt/elastic-internal/kibana-plugins-local
            name: kibana-plugins
          - mountPath: /mnt/elastic-internal/scripts
            name: kibana-scripts
            readOnly: true
          - mountPath: /tmp
            name: temp-volume
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1000
        terminationGracePeriodSeconds: 30
        volumes:
        - name: elastic-internal-http-certificates
          secret:
            defaultMode: 420
            optional: false
            secretName: kibana-kb-http-certs-internal
        - name: elastic-internal-kibana-config
          secret:
            defaultMode: 420
            optional: false
            secretName: kibana-kb-config
        - emptyDir: {}
          name: elastic-internal-kibana-config-local
        - name: elasticsearch-certs
          secret:
            defaultMode: 420
            optional: false
            secretName: kibana-kb-es-ca
        - emptyDir: {}
          name: kibana-data
        - emptyDir: {}
          name: kibana-logs
        - emptyDir: {}
          name: kibana-plugins
        - configMap:
            defaultMode: 493
            name: kibana-kb-scripts
            optional: false
          name: kibana-scripts
        - emptyDir: {}
          name: temp-volume
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-02-25T23:46:16Z"
      lastUpdateTime: "2026-02-25T23:46:16Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2026-02-13T19:05:45Z"
      lastUpdateTime: "2026-02-27T09:00:11Z"
      message: ReplicaSet "kibana-kb-558fcc5bdc" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 5
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
