apiVersion: v1
data:
  elastic: UXFiOFlUaVhVREthRTJ3cUFYN0p0dk1u
kind: Secret
metadata:
  creationTimestamp: "2026-02-27T09:00:10Z"
  labels:
    common.k8s.elastic.co/type: elasticsearch
    eck.k8s.elastic.co/credentials: "true"
    eck.k8s.elastic.co/owner-kind: Elasticsearch
    eck.k8s.elastic.co/owner-name: logging
    eck.k8s.elastic.co/owner-namespace: observability
    elasticsearch.k8s.elastic.co/cluster-name: logging
  name: logging-es-elastic-user
  namespace: observability
  resourceVersion: "6201907"
  uid: ba4442c9-2fab-44d0-bca4-7a3ed86b41dd
type: Opaque
