apiVersion: v1
data:
  hash: e1BCS0RGMl9TVFJFVENIfTEwMDAwJFowQWRFUnJWb2Z1OEtab0xrc3hNSmJtbHJDV2oxUlN6S1JtbHVMU1R0d0E9JHMwbVlIeEtESnJ0VFZjUUdHRzByUCs5bFVqbURLTTFJTVFpbnlPRW1Rbnc9
  name: ZWxhc3RpYy9raWJhbmEvb2JzZXJ2YWJpbGl0eV9raWJhbmFfZDljMjI5ZDctZWVkMy00NWJiLWFmNGQtNDc0M2MwODk0OGVk
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: observability:/Secret:observability/observability-kibana-kibana-user
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"hash":"e1BCS0RGMl9TVFJFVENIfTEwMDAwJFowQWRFUnJWb2Z1OEtab0xrc3hNSmJtbHJDV2oxUlN6S1JtbHVMU1R0d0E9JHMwbVlIeEtESnJ0VFZjUUdHRzByUCs5bFVqbURLTTFJTVFpbnlPRW1Rbnc9","name":"ZWxhc3RpYy9raWJhbmEvb2JzZXJ2YWJpbGl0eV9raWJhbmFfZDljMjI5ZDctZWVkMy00NWJiLWFmNGQtNDc0M2MwODk0OGVk"},"kind":"Secret","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"observability:/Secret:observability/observability-kibana-kibana-user"},"creationTimestamp":"2026-02-13T19:05:44Z","labels":{"common.k8s.elastic.co/type":"service-account-token","elasticsearch.k8s.elastic.co/cluster-name":"logging","elasticsearch.k8s.elastic.co/cluster-namespace":"observability","kibanaassociation.k8s.elastic.co/name":"kibana","kibanaassociation.k8s.elastic.co/namespace":"observability","kibanaassociation.k8s.elastic.co/type":"elasticsearch"},"name":"observability-kibana-kibana-user","namespace":"observability","ownerReferences":[{"apiVersion":"elasticsearch.k8s.elastic.co/v1","blockOwnerDeletion":true,"controller":true,"kind":"Elasticsearch","name":"logging","uid":"1c4aeb4c-afb2-4714-b3b0-d1d756f53bdc"}],"resourceVersion":"2112985","uid":"3cbc75d2-868e-4237-b25c-0dadcbf6eab4"},"type":"Opaque"}
  creationTimestamp: "2026-02-13T19:05:44Z"
  labels:
    common.k8s.elastic.co/type: service-account-token
    elasticsearch.k8s.elastic.co/cluster-name: logging
    elasticsearch.k8s.elastic.co/cluster-namespace: observability
    kibanaassociation.k8s.elastic.co/name: kibana
    kibanaassociation.k8s.elastic.co/namespace: observability
    kibanaassociation.k8s.elastic.co/type: elasticsearch
  name: observability-kibana-kibana-user
  namespace: observability
  ownerReferences:
  - apiVersion: elasticsearch.k8s.elastic.co/v1
    blockOwnerDeletion: true
    controller: true
    kind: Elasticsearch
    name: logging
    uid: 1c4aeb4c-afb2-4714-b3b0-d1d756f53bdc
  resourceVersion: "6188175"
  uid: 3cbc75d2-868e-4237-b25c-0dadcbf6eab4
type: Opaque
