apiVersion: v1
data:
  settings.json: eyJtZXRhZGF0YSI6eyJ2ZXJzaW9uIjoiMTc3MTAwOTUyOTY0NDQ4NDI5NSIsImNvbXBhdGliaWxpdHkiOiI4LjYuMSJ9LCJzdGF0ZSI6eyJjbHVzdGVyX3NldHRpbmdzIjp7fSwic25hcHNob3RfcmVwb3NpdG9yaWVzIjp7fSwic2xtIjp7fSwicm9sZV9tYXBwaW5ncyI6e30sImlsbSI6e30sImluZ2VzdF9waXBlbGluZXMiOnt9LCJpbmRleF90ZW1wbGF0ZXMiOnsiY29tcG9uZW50X3RlbXBsYXRlcyI6e30sImNvbXBvc2FibGVfaW5kZXhfdGVtcGxhdGVzIjp7fX19fQ==
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: observability:/Secret:observability/logging-es-file-settings
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"settings.json":"eyJtZXRhZGF0YSI6eyJ2ZXJzaW9uIjoiMTc3MTAwOTUyOTY0NDQ4NDI5NSIsImNvbXBhdGliaWxpdHkiOiI4LjYuMSJ9LCJzdGF0ZSI6eyJjbHVzdGVyX3NldHRpbmdzIjp7fSwic25hcHNob3RfcmVwb3NpdG9yaWVzIjp7fSwic2xtIjp7fSwicm9sZV9tYXBwaW5ncyI6e30sImlsbSI6e30sImluZ2VzdF9waXBlbGluZXMiOnt9LCJpbmRleF90ZW1wbGF0ZXMiOnsiY29tcG9uZW50X3RlbXBsYXRlcyI6e30sImNvbXBvc2FibGVfaW5kZXhfdGVtcGxhdGVzIjp7fX19fQ=="},"kind":"Secret","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"observability:/Secret:observability/logging-es-file-settings","policy.k8s.elastic.co/settings-hash":"282389006"},"creationTimestamp":"2026-02-13T19:05:29Z","labels":{"asset.policy.k8s.elastic.co/on-delete":"reset","common.k8s.elastic.co/type":"elasticsearch","elasticsearch.k8s.elastic.co/cluster-name":"logging"},"name":"logging-es-file-settings","namespace":"observability","ownerReferences":[{"apiVersion":"elasticsearch.k8s.elastic.co/v1","blockOwnerDeletion":true,"controller":true,"kind":"Elasticsearch","name":"logging","uid":"1c4aeb4c-afb2-4714-b3b0-d1d756f53bdc"}],"resourceVersion":"2112797","uid":"50810a9f-0278-4e9e-bb2e-0dbe3f3fae79"},"type":"Opaque"}
    policy.k8s.elastic.co/settings-hash: "282389006"
  creationTimestamp: "2026-02-13T19:05:29Z"
  labels:
    asset.policy.k8s.elastic.co/on-delete: reset
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: logging
  name: logging-es-file-settings
  namespace: observability
  ownerReferences:
  - apiVersion: elasticsearch.k8s.elastic.co/v1
    blockOwnerDeletion: true
    controller: true
    kind: Elasticsearch
    name: logging
    uid: 1c4aeb4c-afb2-4714-b3b0-d1d756f53bdc
  resourceVersion: "6188169"
  uid: 50810a9f-0278-4e9e-bb2e-0dbe3f3fae79
type: Opaque
