apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTRENDQWpDZ0F3SUJBZ0lSQU53TUh3NUQ1Q2tneHVlRWYzNmRJTG93RFFZSktvWklodmNOQVFFTEJRQXcKTGpFUU1BNEdBMVVFQ3hNSGJHOW5aMmx1WnpFYU1CZ0dBMVVFQXhNUmJHOW5aMmx1WnkxMGNtRnVjM0J2Y25RdwpIaGNOTWpZd01qRXpNVGcxTlRJNVdoY05NamN3TWpFek1Ua3dOVEk1V2pBdU1SQXdEZ1lEVlFRTEV3ZHNiMmRuCmFXNW5NUm93R0FZRFZRUURFeEZzYjJkbmFXNW5MWFJ5WVc1emNHOXlkRENDQVNJd0RRWUpLb1pJaHZjTkFRRUIKQlFBRGdnRVBBRENDQVFvQ2dnRUJBTzV0d01mam52aWJEVHNZcTBIcGxpTkVZTDFpdzA2bWZ2eCtKamJCNWdkawppT25lVFIvT3RWbVNBQ0t4Tng0UEVZRkZQRGJrUkJOcEJxMHJPbytvdzQxNVZKcTVheHpXblBkYlVyRzRITzhuCk5tSmEyd0xPWnFZZGl4cyswOXlsZXFBNkVVUS9vVEtUWGpPbVZjYkthYzZxWHVzcWVCVERGUndtcmhsQTR6d2sKMlgrWkJ5NGlGRlQrcmtTU3hOcVZYSlY2VUxpYTBDa1Vnc3UyUjVnVjJ5eUswczhEckltZXdSK01ldXF6VTczSApURkpQUWdHajRWSXBiMk1oQS9OdlJQM01RdmFFZFFvUVo1ZUdKRXY0VWhueXNMeXV3S2dNOVI0d3h4TUhRbG4vCjZjQXJ0Q0ZGNGM5dWl2Snh1U1ROU3o0YURiWTlYdlptRmxORUVucjF4QUVDQXdFQUFhTmhNRjh3RGdZRFZSMFAKQVFIL0JBUURBZ0tFTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQgpBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlMxRk5HbVRyeVBvZmVudnVzY1ZPVFdRMHFoUkRBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFORkJ4TVlKUHd0M21wQWVRUldQWE9ORzAyVDViNDZ2OXFpTmtORXJiSnVkZ3dqc0QKcU9YR1ZXR1BSUytUaE1CSlh1eWVuaWt6aHNmSEMxd3hXaWJPZnVVcEFYbXlWQlIyb3JRRm0rclFYRWZBZUlHNwoyK1lCcXMwTFBYSUxUOHZiVndHc0pMTk5aWTJkT3ovVmw1c1B6WC92T3pCenZVdUliTCtBalR4YVdnUkhGRTlGCnkwWFJHRWFwemZPYUFOTHFvbTRkOXY1M0cydlZoS0RBNTV5cllWWDdXVHN3OEZzczFwZkZ4QmVuYVRzM0FXeEsKMFFUUW5HRDh2QVZnV2szNzBkVy91RDRrVmtXMkRLajAwemF4V0t0T2xUS0xZUDV0UEpiNW9qVDh4d3d0T2c1TwpxVkd6cEwwS1JCa1o0VUxrWUVHZDF1bVRQd05nSkk0VlNCcnlWUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
kind: Secret
metadata:
  creationTimestamp: "2026-02-27T09:00:09Z"
  labels:
    common.k8s.elastic.co/type: elasticsearch
    eck.k8s.elastic.co/owner-kind: Elasticsearch
    eck.k8s.elastic.co/owner-name: logging
    eck.k8s.elastic.co/owner-namespace: observability
    elasticsearch.k8s.elastic.co/cluster-name: logging
  name: logging-es-transport-certs-public
  namespace: observability
  resourceVersion: "6201874"
  uid: db58c11f-d173-4066-ad95-10b8b98d46c3
type: Opaque
