apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-02-13T19:05:16Z"
    name: default
    namespace: observability
    resourceVersion: "2112714"
    uid: 9931ca45-e1a5-400e-8da4-7c335e4b208e
kind: List
metadata:
  resourceVersion: ""
