apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: portfolio:/Service:abu7midan-website/portfolio
    field.cattle.io/publicEndpoints: '[{"port":30154,"protocol":"TCP","serviceName":"abu7midan-website:portfolio","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"portfolio:/Service:abu7midan-website/portfolio","field.cattle.io/publicEndpoints":"[{\"port\":30154,\"protocol\":\"TCP\",\"serviceName\":\"abu7midan-website:portfolio\",\"allNodes\":true}]"},"creationTimestamp":"2026-02-26T00:25:05Z","labels":{"app":"portfolio"},"name":"portfolio","namespace":"abu7midan-website","resourceVersion":"5799121","uid":"da370f3a-1432-460b-8380-d0805e77a731"},"spec":{"clusterIP":"10.96.31.64","clusterIPs":["10.96.31.64"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"http","nodePort":30154,"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"portfolio"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2026-02-26T00:25:05Z"
  labels:
    app: portfolio
  name: portfolio
  namespace: abu7midan-website
  resourceVersion: "6185658"
  uid: da370f3a-1432-460b-8380-d0805e77a731
spec:
  clusterIP: 10.96.31.64
  clusterIPs:
    - 10.96.31.64
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      nodePort: 30154
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: portfolio
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
