apiVersion: v1
data:
  uuid: 6edc5ee5-c678-42ee-ab44-29c289c9cb96
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: elastic-system:/ConfigMap:elastic-system/elastic-operator-uuid
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"uuid":"6edc5ee5-c678-42ee-ab44-29c289c9cb96"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"elastic-system:/ConfigMap:elastic-system/elastic-operator-uuid"},"creationTimestamp":"2026-02-13T19:04:31Z","name":"elastic-operator-uuid","namespace":"elastic-system","resourceVersion":"2112526","uid":"6f4af539-cf26-4fe6-b468-2e276d6ad56e"}}
  creationTimestamp: "2026-02-13T19:04:31Z"
  name: elastic-operator-uuid
  namespace: elastic-system
  resourceVersion: "6186585"
  uid: 6f4af539-cf26-4fe6-b468-2e276d6ad56e
