apiVersion: v1
data:
  apm_memory: 0.00GiB
  apm_memory_bytes: "0"
  eck_license_level: basic
  elasticsearch_memory: 3.00GiB
  elasticsearch_memory_bytes: "3221225472"
  enterprise_resource_units: "1"
  enterprise_search_memory: 0.00GiB
  enterprise_search_memory_bytes: "0"
  kibana_memory: 1.00GiB
  kibana_memory_bytes: "1073741824"
  logstash_memory: 0.00GiB
  logstash_memory_bytes: "0"
  timestamp: "2026-02-25T23:43:16Z"
  total_managed_memory: 4.00GiB
  total_managed_memory_bytes: "4294967296"
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: elastic-system:/ConfigMap:elastic-system/elastic-licensing
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"apm_memory":"0.00GiB","apm_memory_bytes":"0","eck_license_level":"basic","elasticsearch_memory":"3.00GiB","elasticsearch_memory_bytes":"3221225472","enterprise_resource_units":"1","enterprise_search_memory":"0.00GiB","enterprise_search_memory_bytes":"0","kibana_memory":"1.00GiB","kibana_memory_bytes":"1073741824","logstash_memory":"0.00GiB","logstash_memory_bytes":"0","timestamp":"2026-02-25T23:43:16Z","total_managed_memory":"4.00GiB","total_managed_memory_bytes":"4294967296"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"elastic-system:/ConfigMap:elastic-system/elastic-licensing"},"creationTimestamp":"2026-02-13T19:04:43Z","labels":{"common.k8s.elastic.co/type":"elastic-usage"},"name":"elastic-licensing","namespace":"elastic-system","resourceVersion":"5770214","uid":"3e3627ae-19ec-48e6-8e24-ae049faf4b47"}}
  creationTimestamp: "2026-02-13T19:04:43Z"
  labels:
    common.k8s.elastic.co/type: elastic-usage
  name: elastic-licensing
  namespace: elastic-system
  resourceVersion: "6186598"
  uid: 3e3627ae-19ec-48e6-8e24-ae049faf4b47
apiVersion: v1
data:
  eck.yaml: |-
    log-verbosity: 0
    metrics-port: 0
    metrics-secure: false
    container-registry: docker.elastic.co
    max-concurrent-reconciles: 3
    ca-cert-validity: 8760h
    ca-cert-rotate-before: 24h
    cert-validity: 8760h
    cert-rotate-before: 24h
    disable-config-watch: false
    exposed-node-labels: [topology.kubernetes.io/.*,failure-domain.beta.kubernetes.io/.*]
    set-default-security-context: auto-detect
    kube-client-timeout: 60s
    elasticsearch-client-timeout: 180s
    disable-telemetry: false
    distribution-channel: all-in-one
    validate-storage-class: true
    enable-webhook: true
    webhook-name: elastic-webhook.k8s.elastic.co
    webhook-port: 9443
    operator-namespace: elastic-system
    enable-leader-election: true
    elasticsearch-observation-interval: 10s
    ubi-only: false
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: elastic-system:/ConfigMap:elastic-system/elastic-operator
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"eck.yaml":"log-verbosity: 0\nmetrics-port: 0\nmetrics-secure: false\ncontainer-registry: docker.elastic.co\nmax-concurrent-reconciles: 3\nca-cert-validity: 8760h\nca-cert-rotate-before: 24h\ncert-validity: 8760h\ncert-rotate-before: 24h\ndisable-config-watch: false\nexposed-node-labels: [topology.kubernetes.io/.*,failure-domain.beta.kubernetes.io/.*]\nset-default-security-context: auto-detect\nkube-client-timeout: 60s\nelasticsearch-client-timeout: 180s\ndisable-telemetry: false\ndistribution-channel: all-in-one\nvalidate-storage-class: true\nenable-webhook: true\nwebhook-name: elastic-webhook.k8s.elastic.co\nwebhook-port: 9443\noperator-namespace: elastic-system\nenable-leader-election: true\nelasticsearch-observation-interval: 10s\nubi-only: false"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"elastic-system:/ConfigMap:elastic-system/elastic-operator"},"creationTimestamp":"2026-02-13T19:04:24Z","labels":{"app.kubernetes.io/version":"3.3.0","control-plane":"elastic-operator"},"name":"elastic-operator","namespace":"elastic-system","resourceVersion":"2112469","uid":"7dba73e1-46dc-4177-98ad-d8945bf5e6a4"}}
  creationTimestamp: "2026-02-13T19:04:24Z"
  labels:
    app.kubernetes.io/version: 3.3.0
    control-plane: elastic-operator
  name: elastic-operator
  namespace: elastic-system
  resourceVersion: "6186606"
  uid: 7dba73e1-46dc-4177-98ad-d8945bf5e6a4
apiVersion: v1
data:
  uuid: 6edc5ee5-c678-42ee-ab44-29c289c9cb96
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: elastic-system:/ConfigMap:elastic-system/elastic-operator-uuid
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"uuid":"6edc5ee5-c678-42ee-ab44-29c289c9cb96"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"elastic-system:/ConfigMap:elastic-system/elastic-operator-uuid"},"creationTimestamp":"2026-02-13T19:04:31Z","name":"elastic-operator-uuid","namespace":"elastic-system","resourceVersion":"2112526","uid":"6f4af539-cf26-4fe6-b468-2e276d6ad56e"}}
  creationTimestamp: "2026-02-13T19:04:31Z"
  name: elastic-operator-uuid
  namespace: elastic-system
  resourceVersion: "6186585"
  uid: 6f4af539-cf26-4fe6-b468-2e276d6ad56e
