apiVersion: v1
items:
- apiVersion: v1
  data:
    apm_memory: 0.00GiB
    apm_memory_bytes: "0"
    eck_license_level: basic
    elasticsearch_memory: 3.00GiB
    elasticsearch_memory_bytes: "3221225472"
    enterprise_resource_units: "1"
    enterprise_search_memory: 0.00GiB
    enterprise_search_memory_bytes: "0"
    kibana_memory: 1.00GiB
    kibana_memory_bytes: "1073741824"
    logstash_memory: 0.00GiB
    logstash_memory_bytes: "0"
    timestamp: "2026-02-25T23:43:16Z"
    total_managed_memory: 4.00GiB
    total_managed_memory_bytes: "4294967296"
  kind: ConfigMap
  metadata:
    creationTimestamp: "2026-02-13T19:04:43Z"
    labels:
      common.k8s.elastic.co/type: elastic-usage
    name: elastic-licensing
    namespace: elastic-system
    resourceVersion: "5770214"
    uid: 3e3627ae-19ec-48e6-8e24-ae049faf4b47
- apiVersion: v1
  data:
    eck.yaml: |-
      log-verbosity: 0
      metrics-port: 0
      metrics-secure: false
      container-registry: docker.elastic.co
      max-concurrent-reconciles: 3
      ca-cert-validity: 8760h
      ca-cert-rotate-before: 24h
      cert-validity: 8760h
      cert-rotate-before: 24h
      disable-config-watch: false
      exposed-node-labels: [topology.kubernetes.io/.*,failure-domain.beta.kubernetes.io/.*]
      set-default-security-context: auto-detect
      kube-client-timeout: 60s
      elasticsearch-client-timeout: 180s
      disable-telemetry: false
      distribution-channel: all-in-one
      validate-storage-class: true
      enable-webhook: true
      webhook-name: elastic-webhook.k8s.elastic.co
      webhook-port: 9443
      operator-namespace: elastic-system
      enable-leader-election: true
      elasticsearch-observation-interval: 10s
      ubi-only: false
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"eck.yaml":"log-verbosity: 0\nmetrics-port: 0\nmetrics-secure: false\ncontainer-registry: docker.elastic.co\nmax-concurrent-reconciles: 3\nca-cert-validity: 8760h\nca-cert-rotate-before: 24h\ncert-validity: 8760h\ncert-rotate-before: 24h\ndisable-config-watch: false\nexposed-node-labels: [topology.kubernetes.io/.*,failure-domain.beta.kubernetes.io/.*]\nset-default-security-context: auto-detect\nkube-client-timeout: 60s\nelasticsearch-client-timeout: 180s\ndisable-telemetry: false\ndistribution-channel: all-in-one\nvalidate-storage-class: true\nenable-webhook: true\nwebhook-name: elastic-webhook.k8s.elastic.co\nwebhook-port: 9443\noperator-namespace: elastic-system\nenable-leader-election: true\nelasticsearch-observation-interval: 10s\nubi-only: false"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/version":"3.3.0","control-plane":"elastic-operator"},"name":"elastic-operator","namespace":"elastic-system"}}
    creationTimestamp: "2026-02-13T19:04:24Z"
    labels:
      app.kubernetes.io/version: 3.3.0
      control-plane: elastic-operator
    name: elastic-operator
    namespace: elastic-system
    resourceVersion: "2112469"
    uid: 7dba73e1-46dc-4177-98ad-d8945bf5e6a4
- apiVersion: v1
  data:
    uuid: 6edc5ee5-c678-42ee-ab44-29c289c9cb96
  kind: ConfigMap
  metadata:
    creationTimestamp: "2026-02-13T19:04:31Z"
    name: elastic-operator-uuid
    namespace: elastic-system
    resourceVersion: "2112526"
    uid: 6f4af539-cf26-4fe6-b468-2e276d6ad56e
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIDqtKmA2hLZYwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjAxMzAxMDE3MTVaFw0zNjAxMjgxMDIyMTVaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQDAa+5Kr9G5n1h+BeHS4t41RkUCtR0s+zc3odysP/vj7hmrCGcW8tx+6PLD
      AqcGki9/uEQ0Te7kL55lI/rPbT3e1MsoduokwS3tMj5hHZoKlbE+TflcFsdX2KSG
      L45UwL4RifrdAGGK+dGpdL+gN1Cvh0ykNibx73Wm+ObfAYH2vkr2gtttnW9j6w+y
      AVVCpLzFBQtdlLluGLQZe7gW20kmU7zJmeZkixZLerW7QNXH8uSt2WAfBSCnOM2e
      WiYgz6qUIZPrBHQ5Zkl0xLFTLulKbPJRvxXdwSQbsObpq/G/mXvWiVX+64ZwNLpK
      aUQHnUGHPm5m3livNpneSGHS7xQXAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSg9wtwOXh5UxEu+26CNSwkbpS4LTAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQB7mdzAzYgL
      LbaQANU6H2H15cOeN+Jz4lqnUqo5Mqla9I2xd3YcczugEnVApaHz8vmLCEIq6fI0
      5rpcml1b/wmP3IbC57nnhcqfCKm+3G48uDxK7JCRJrfI0VDg0ZkImZEd5J5EUNIi
      nnppYBWKLbwtLi2aooGPtBExruN1o6rKit7g0kFPwoYGGOEBaF1sKGBy98w5EEs/
      L9fVWXP2V/v0Gu+lTfsasZZ/jlmjM2Tm7671T95+xnGDQDoM8CmgUP3E0QV9/ug0
      /L+iIMOLD5DgN1fp7T5iNoWPEd6hcNuZxjHGHFMp0lA7Zn4TraYQih69lmQjtlx1
      6uooniAO0xc2
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-02-13T19:04:23Z"
    name: kube-root-ca.crt
    namespace: elastic-system
    resourceVersion: "2112466"
    uid: 21206ffd-c297-4a51-a151-b75869c927e2
kind: List
metadata:
  resourceVersion: ""
