apiVersion: v1
data:
  eck.yaml: |-
    log-verbosity: 0
    metrics-port: 0
    metrics-secure: false
    container-registry: docker.elastic.co
    max-concurrent-reconciles: 3
    ca-cert-validity: 8760h
    ca-cert-rotate-before: 24h
    cert-validity: 8760h
    cert-rotate-before: 24h
    disable-config-watch: false
    exposed-node-labels: [topology.kubernetes.io/.*,failure-domain.beta.kubernetes.io/.*]
    set-default-security-context: auto-detect
    kube-client-timeout: 60s
    elasticsearch-client-timeout: 180s
    disable-telemetry: false
    distribution-channel: all-in-one
    validate-storage-class: true
    enable-webhook: true
    webhook-name: elastic-webhook.k8s.elastic.co
    webhook-port: 9443
    operator-namespace: elastic-system
    enable-leader-election: true
    elasticsearch-observation-interval: 10s
    ubi-only: false
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: elastic-system:/ConfigMap:elastic-system/elastic-operator
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"eck.yaml":"log-verbosity: 0\nmetrics-port: 0\nmetrics-secure: false\ncontainer-registry: docker.elastic.co\nmax-concurrent-reconciles: 3\nca-cert-validity: 8760h\nca-cert-rotate-before: 24h\ncert-validity: 8760h\ncert-rotate-before: 24h\ndisable-config-watch: false\nexposed-node-labels: [topology.kubernetes.io/.*,failure-domain.beta.kubernetes.io/.*]\nset-default-security-context: auto-detect\nkube-client-timeout: 60s\nelasticsearch-client-timeout: 180s\ndisable-telemetry: false\ndistribution-channel: all-in-one\nvalidate-storage-class: true\nenable-webhook: true\nwebhook-name: elastic-webhook.k8s.elastic.co\nwebhook-port: 9443\noperator-namespace: elastic-system\nenable-leader-election: true\nelasticsearch-observation-interval: 10s\nubi-only: false"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"elastic-system:/ConfigMap:elastic-system/elastic-operator"},"creationTimestamp":"2026-02-13T19:04:24Z","labels":{"app.kubernetes.io/version":"3.3.0","control-plane":"elastic-operator"},"name":"elastic-operator","namespace":"elastic-system","resourceVersion":"2112469","uid":"7dba73e1-46dc-4177-98ad-d8945bf5e6a4"}}
  creationTimestamp: "2026-02-13T19:04:24Z"
  labels:
    app.kubernetes.io/version: 3.3.0
    control-plane: elastic-operator
  name: elastic-operator
  namespace: elastic-system
  resourceVersion: "6186606"
  uid: 7dba73e1-46dc-4177-98ad-d8945bf5e6a4
