apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmaps.yaml
- deployment.yaml
- ingress.yaml
- networkpolicies.yaml
- pvc.yaml
- secret-NAME.yaml
- secret-sh.helm.release.v1.vault.v1.yaml
- secret-vault-abu7midan-tls.yaml
- secret-vault-auth-token.yaml
- serviceaccounts.yaml
- services.yaml

namespace: vault
