apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-02-15T18:05:00Z"
    name: default
    namespace: vault
    resourceVersion: "2768043"
    uid: d9e8ab8c-b84c-4e54-abdb-76639d537dc4
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: vault
      meta.helm.sh/release-namespace: vault
    creationTimestamp: "2026-02-15T18:05:03Z"
    labels:
      app.kubernetes.io/instance: vault
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: vault
      helm.sh/chart: vault-0.32.0
    name: vault
    namespace: vault
    resourceVersion: "2768059"
    uid: d80ad0ed-298b-4b77-93d8-3ce77969428f
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: vault
      meta.helm.sh/release-namespace: vault
    creationTimestamp: "2026-02-15T18:05:03Z"
    labels:
      app.kubernetes.io/instance: vault
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: vault-agent-injector
    name: vault-agent-injector
    namespace: vault
    resourceVersion: "2768061"
    uid: 455f3307-73e7-4575-9a42-96aaa98df19c
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-02-15T18:21:13Z"
    name: vault-auth
    namespace: vault
    resourceVersion: "2772215"
    uid: 8384b430-1acb-42a9-91e2-64b1a932613c
kind: List
metadata:
  resourceVersion: ""
