apiVersion: v1
items:
- apiVersion: v1
  data:
    fluent-bit.conf: |
      [SERVICE]
          Flush                     1
          Daemon                    Off
          Log_Level                 info
          Parsers_File              parsers.conf
          storage.path              /tmp/flb-storage
          storage.sync              normal
          storage.checksum          off
          storage.max_chunks_up     256

      # ONLY kong namespace logs
      [INPUT]
          Name                      tail
          Path                      /var/log/containers/*_kong_*.log
          Parser                    cri
          Tag                       kong.*
          Mem_Buf_Limit             256MB
          Skip_Long_Lines           On
          Refresh_Interval          5
          storage.type              filesystem

      [FILTER]
          Name                      kubernetes
          Match                     kong.*
          Kube_URL                  https://kubernetes.default.svc:443
          Kube_CA_File              /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          Kube_Token_File           /var/run/secrets/kubernetes.io/serviceaccount/token
          Merge_Log                 On
          Keep_Log                  On
          K8S-Logging.Parser        On
          K8S-Logging.Exclude       On

      # TEMP: don't grep proxy yet (until we confirm the real container name/file)
      # We'll add it back after we confirm the right container log filename.

      [OUTPUT]
          Name                      es
          Match                     kong.*
          Host                      logging-es-http.observability.svc
          Port                      9200
          TLS                       On
          TLS.Verify                Off
          HTTP_User                 ${ES_USER}
          HTTP_Passwd               ${ES_PASS}
          Logstash_Format           On
          Logstash_Prefix           kong-traffic
          Replace_Dots              On
          Suppress_Type_Name        On
          Trace_Error               On
    parsers.conf: |
      [PARSER]
          Name        cri
          Format      regex
          Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
          Time_Key    time
          Time_Format %Y-%m-%dT%H:%M:%S.%L%z
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"fluent-bit.conf":"[SERVICE]\n    Flush                     1\n    Daemon                    Off\n    Log_Level                 info\n    Parsers_File              parsers.conf\n    storage.path              /tmp/flb-storage\n    storage.sync              normal\n    storage.checksum          off\n    storage.max_chunks_up     256\n\n# ONLY kong namespace logs\n[INPUT]\n    Name                      tail\n    Path                      /var/log/containers/*_kong_*.log\n    Parser                    cri\n    Tag                       kong.*\n    Mem_Buf_Limit             256MB\n    Skip_Long_Lines           On\n    Refresh_Interval          5\n    storage.type              filesystem\n\n[FILTER]\n    Name                      kubernetes\n    Match                     kong.*\n    Kube_URL                  https://kubernetes.default.svc:443\n    Kube_CA_File              /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n    Kube_Token_File           /var/run/secrets/kubernetes.io/serviceaccount/token\n    Merge_Log                 On\n    Keep_Log                  On\n    K8S-Logging.Parser        On\n    K8S-Logging.Exclude       On\n\n# TEMP: don't grep proxy yet (until we confirm the real container name/file)\n# We'll add it back after we confirm the right container log filename.\n\n[OUTPUT]\n    Name                      es\n    Match                     kong.*\n    Host                      logging-es-http.observability.svc\n    Port                      9200\n    TLS                       On\n    TLS.Verify                Off\n    HTTP_User                 ${ES_USER}\n    HTTP_Passwd               ${ES_PASS}\n    Logstash_Format           On\n    Logstash_Prefix           kong-traffic\n    Replace_Dots              On\n    Suppress_Type_Name        On\n    Trace_Error               On\n","parsers.conf":"[PARSER]\n    Name        cri\n    Format      regex\n    Regex       ^(?\u003ctime\u003e[^ ]+) (?\u003cstream\u003estdout|stderr) (?\u003clogtag\u003e[^ ]*) (?\u003clog\u003e.*)$\n    Time_Key    time\n    Time_Format %Y-%m-%dT%H:%M:%S.%L%z\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"fluent-bit-config","namespace":"logging"}}
    creationTimestamp: "2026-02-13T21:47:19Z"
    name: fluent-bit-config
    namespace: logging
    resourceVersion: "2152937"
    uid: ce300cfd-f71e-42ba-b2c5-9c7e3a3e0e99
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIDqtKmA2hLZYwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNjAxMzAxMDE3MTVaFw0zNjAxMjgxMDIyMTVaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQDAa+5Kr9G5n1h+BeHS4t41RkUCtR0s+zc3odysP/vj7hmrCGcW8tx+6PLD
      AqcGki9/uEQ0Te7kL55lI/rPbT3e1MsoduokwS3tMj5hHZoKlbE+TflcFsdX2KSG
      L45UwL4RifrdAGGK+dGpdL+gN1Cvh0ykNibx73Wm+ObfAYH2vkr2gtttnW9j6w+y
      AVVCpLzFBQtdlLluGLQZe7gW20kmU7zJmeZkixZLerW7QNXH8uSt2WAfBSCnOM2e
      WiYgz6qUIZPrBHQ5Zkl0xLFTLulKbPJRvxXdwSQbsObpq/G/mXvWiVX+64ZwNLpK
      aUQHnUGHPm5m3livNpneSGHS7xQXAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSg9wtwOXh5UxEu+26CNSwkbpS4LTAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQB7mdzAzYgL
      LbaQANU6H2H15cOeN+Jz4lqnUqo5Mqla9I2xd3YcczugEnVApaHz8vmLCEIq6fI0
      5rpcml1b/wmP3IbC57nnhcqfCKm+3G48uDxK7JCRJrfI0VDg0ZkImZEd5J5EUNIi
      nnppYBWKLbwtLi2aooGPtBExruN1o6rKit7g0kFPwoYGGOEBaF1sKGBy98w5EEs/
      L9fVWXP2V/v0Gu+lTfsasZZ/jlmjM2Tm7671T95+xnGDQDoM8CmgUP3E0QV9/ug0
      /L+iIMOLD5DgN1fp7T5iNoWPEd6hcNuZxjHGHFMp0lA7Zn4TraYQih69lmQjtlx1
      6uooniAO0xc2
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-02-13T19:49:17Z"
    name: kube-root-ca.crt
    namespace: logging
    resourceVersion: "2123919"
    uid: 5815236b-cb78-40c9-aea5-68d499f70eb2
kind: List
metadata:
  resourceVersion: ""
