apiVersion: v1
data:
  ES_PASS: azhsb2dnZXI=
  ES_USER: azhsb2dnZXI=
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: logging:/Secret:logging/elastic-creds
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ES_PASS":"azhsb2dnZXI=","ES_USER":"azhsb2dnZXI="},"kind":"Secret","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"logging:/Secret:logging/elastic-creds"},"creationTimestamp":"2026-02-13T20:02:14Z","name":"elastic-creds","namespace":"logging","resourceVersion":"2127129","uid":"19ce665d-71d7-4c84-80a0-1b37b00c9ed1"},"type":"Opaque"}
  creationTimestamp: "2026-02-13T20:02:14Z"
  name: elastic-creds
  namespace: logging
  resourceVersion: "6186570"
  uid: 19ce665d-71d7-4c84-80a0-1b37b00c9ed1
type: Opaque
apiVersion: v1
data:
  ES_PASS: b2V5czYwYjB0eUxMRzVwbDlMQmloWHg4
  ES_USER: ZWxhc3RpYw==
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: logging:/Secret:logging/es-credentials
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ES_PASS":"b2V5czYwYjB0eUxMRzVwbDlMQmloWHg4","ES_USER":"ZWxhc3RpYw=="},"kind":"Secret","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"logging:/Secret:logging/es-credentials"},"creationTimestamp":"2026-02-13T19:50:28Z","name":"es-credentials","namespace":"logging","resourceVersion":"2143588","uid":"75a26a9e-9a8a-4ab1-a6a7-b57757fd5bdb"},"type":"Opaque"}
  creationTimestamp: "2026-02-13T19:50:28Z"
  name: es-credentials
  namespace: logging
  resourceVersion: "6186568"
  uid: 75a26a9e-9a8a-4ab1-a6a7-b57757fd5bdb
type: Opaque
apiVersion: v1
data:
  ES_PASS: b2V5czYwYjB0eUxMRzVwbDlMQmloWHg4
  ES_USER: ZWxhc3RpYw==
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: logging:/Secret:logging/fluentbit-es-cred
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ES_PASS":"b2V5czYwYjB0eUxMRzVwbDlMQmloWHg4","ES_USER":"ZWxhc3RpYw=="},"kind":"Secret","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"logging:/Secret:logging/fluentbit-es-cred"},"creationTimestamp":"2026-02-13T21:39:28Z","name":"fluentbit-es-cred","namespace":"logging","resourceVersion":"2150706","uid":"5ba81b2c-88be-426e-bc73-90cd94b5b09b"},"type":"Opaque"}
  creationTimestamp: "2026-02-13T21:39:28Z"
  name: fluentbit-es-cred
  namespace: logging
  resourceVersion: "6186569"
  uid: 5ba81b2c-88be-426e-bc73-90cd94b5b09b
type: Opaque
