apiVersion: v1
items:
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: cert-manager:/ServiceAccount:cert-manager/cert-manager
    creationTimestamp: "2026-03-01T23:59:49Z"
    labels:
      app: cert-manager
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/version: v1.19.3
      helm.sh/chart: cert-manager-v1.19.3
    name: cert-manager
    namespace: cert-manager
    resourceVersion: "6887241"
    uid: 43856985-b647-444f-ad9a-e418488259fe
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: cert-manager:/ServiceAccount:cert-manager/cert-manager-cainjector
    creationTimestamp: "2026-03-01T23:59:49Z"
    labels:
      app: cainjector
      app.kubernetes.io/component: cainjector
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: cainjector
      app.kubernetes.io/version: v1.19.3
      helm.sh/chart: cert-manager-v1.19.3
    name: cert-manager-cainjector
    namespace: cert-manager
    resourceVersion: "6887242"
    uid: 6c749155-a1a3-4442-b071-f92fc764fd4d
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: cert-manager:/ServiceAccount:cert-manager/cert-manager-webhook
    creationTimestamp: "2026-03-01T23:59:49Z"
    labels:
      app: webhook
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: webhook
      app.kubernetes.io/version: v1.19.3
      helm.sh/chart: cert-manager-v1.19.3
    name: cert-manager-webhook
    namespace: cert-manager
    resourceVersion: "6887243"
    uid: 113cb516-e36c-4bb6-9518-1fc22345b40f
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-01T23:59:40Z"
    name: default
    namespace: cert-manager
    resourceVersion: "6887204"
    uid: b411e8f9-25f9-4adf-a7d1-ea3d380ea1ff
kind: List
metadata:
  resourceVersion: ""
