apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  annotations:
    association.k8s.elastic.co/es-conf: '{"authSecretName":"kibana-kibana-user","authSecretKey":"token","isApiKey":false,"isServiceAccount":true,"caCertProvided":true,"caSecretName":"kibana-kb-es-ca","url":"https://logging-es-http.observability.svc:9200","version":"9.3.0"}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kibana.k8s.elastic.co/v1","kind":"Kibana","metadata":{"annotations":{},"name":"kibana","namespace":"observability"},"spec":{"count":1,"elasticsearchRef":{"name":"logging"},"version":"9.3.0"}}
  name: kibana
  namespace: observability
spec:
  config:
    server.publicBaseUrl: https://kibana.abu7midan.com
  count: 1
  elasticsearchRef:
    name: logging
  enterpriseSearchRef: {}
  http:
    service:
      metadata: {}
      spec: {}
    tls:
      certificate: {}
  monitoring:
    logs: {}
    metrics: {}
  packageRegistryRef: {}
  podTemplate:
    metadata: {}
    spec:
      containers: null
  version: 9.3.0
