apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: observability:/Service:observability/guestbook-ui
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"observability:/Service:observability/guestbook-ui"},"creationTimestamp":"2026-02-26T04:21:16Z","name":"guestbook-ui","namespace":"observability","resourceVersion":"5841703","uid":"557c631b-a49b-487e-ac81-3ceb4d4c5e7a"},"spec":{"clusterIP":"10.109.190.254","clusterIPs":["10.109.190.254"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"guestbook-ui"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2026-02-26T04:21:16Z"
  name: guestbook-ui
  namespace: observability
  resourceVersion: "6188197"
  uid: 557c631b-a49b-487e-ac81-3ceb4d4c5e7a
spec:
  clusterIP: 10.109.190.254
  clusterIPs:
    - 10.109.190.254
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: guestbook-ui
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
