apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: observability:/Service:observability/guestbook-ui
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"observability:/Service:observability/guestbook-ui"},"creationTimestamp":"2026-02-26T04:21:16Z","name":"guestbook-ui","namespace":"observability","resourceVersion":"5841703","uid":"557c631b-a49b-487e-ac81-3ceb4d4c5e7a"},"spec":{"clusterIP":"10.109.190.254","clusterIPs":["10.109.190.254"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"guestbook-ui"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
      name: guestbook-ui
      namespace: observability
    spec:
      clusterIP: 10.109.190.254
      clusterIPs:
        - 10.109.190.254
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - port: 80
          protocol: TCP
          targetPort: 80
      selector:
        app: guestbook-ui
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: observability:/Service:observability/kibana-kb-http
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"observability:/Service:observability/kibana-kb-http"},"creationTimestamp":"2026-02-13T19:07:46Z","labels":{"common.k8s.elastic.co/type":"kibana","kibana.k8s.elastic.co/name":"kibana"},"name":"kibana-kb-http","namespace":"observability","ownerReferences":[{"apiVersion":"kibana.k8s.elastic.co/v1","blockOwnerDeletion":true,"controller":true,"kind":"Kibana","name":"kibana","uid":"d9c229d7-eed3-45bb-af4d-4743c08948ed"}],"resourceVersion":"4217634","uid":"e689d4f3-67d0-42e6-9ed1-b145b9536097"},"spec":{"clusterIP":"10.105.77.239","clusterIPs":["10.105.77.239"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"https","port":5601,"protocol":"TCP","targetPort":5601}],"selector":{"common.k8s.elastic.co/type":"kibana","kibana.k8s.elastic.co/name":"kibana"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
      labels:
        common.k8s.elastic.co/type: kibana
        kibana.k8s.elastic.co/name: kibana
      name: kibana-kb-http
      namespace: observability
      ownerReferences:
        - apiVersion: kibana.k8s.elastic.co/v1
          blockOwnerDeletion: true
          controller: true
          kind: Kibana
          name: kibana
          uid: d9c229d7-eed3-45bb-af4d-4743c08948ed
    spec:
      clusterIP: 10.105.77.239
      clusterIPs:
        - 10.105.77.239
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: https
          port: 5601
          protocol: TCP
          targetPort: 5601
      selector:
        common.k8s.elastic.co/type: kibana
        kibana.k8s.elastic.co/name: kibana
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: observability:/Service:observability/kibana-nodeport
        field.cattle.io/publicEndpoints: '[{"port":31601,"protocol":"TCP","serviceName":"observability:kibana-nodeport","allNodes":true}]'
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"observability:/Service:observability/kibana-nodeport","field.cattle.io/publicEndpoints":"[{\"port\":31601,\"protocol\":\"TCP\",\"serviceName\":\"observability:kibana-nodeport\",\"allNodes\":true}]"},"creationTimestamp":"2026-02-13T19:25:15Z","name":"kibana-nodeport","namespace":"observability","resourceVersion":"4181034","uid":"2c7bad5d-9bab-48a3-8a9e-8fce77caa1d2"},"spec":{"clusterIP":"10.97.73.56","clusterIPs":["10.97.73.56"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"https","nodePort":31601,"port":5601,"protocol":"TCP","targetPort":5601}],"selector":{"common.k8s.elastic.co/type":"kibana","kibana.k8s.elastic.co/name":"kibana"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
      name: kibana-nodeport
      namespace: observability
    spec:
      clusterIP: 10.97.73.56
      clusterIPs:
        - 10.97.73.56
      externalTrafficPolicy: Cluster
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: https
          nodePort: 31601
          port: 5601
          protocol: TCP
          targetPort: 5601
      selector:
        common.k8s.elastic.co/type: kibana
        kibana.k8s.elastic.co/name: kibana
      sessionAffinity: None
      type: NodePort
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: observability:/Service:observability/logging-es-default
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"observability:/Service:observability/logging-es-default"},"creationTimestamp":"2026-02-13T19:05:29Z","labels":{"common.k8s.elastic.co/type":"elasticsearch","elasticsearch.k8s.elastic.co/cluster-name":"logging","elasticsearch.k8s.elastic.co/statefulset-name":"logging-es-default"},"name":"logging-es-default","namespace":"observability","ownerReferences":[{"apiVersion":"elasticsearch.k8s.elastic.co/v1","blockOwnerDeletion":true,"controller":true,"kind":"Elasticsearch","name":"logging","uid":"1c4aeb4c-afb2-4714-b3b0-d1d756f53bdc"}],"resourceVersion":"2112800","uid":"1734b000-540e-4178-a0de-ea3de159489f"},"spec":{"clusterIP":"None","clusterIPs":["None"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"https","port":9200,"protocol":"TCP","targetPort":9200}],"publishNotReadyAddresses":true,"selector":{"common.k8s.elastic.co/type":"elasticsearch","elasticsearch.k8s.elastic.co/cluster-name":"logging","elasticsearch.k8s.elastic.co/statefulset-name":"logging-es-default"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
      labels:
        common.k8s.elastic.co/type: elasticsearch
        elasticsearch.k8s.elastic.co/cluster-name: logging
        elasticsearch.k8s.elastic.co/statefulset-name: logging-es-default
      name: logging-es-default
      namespace: observability
      ownerReferences:
        - apiVersion: elasticsearch.k8s.elastic.co/v1
          blockOwnerDeletion: true
          controller: true
          kind: Elasticsearch
          name: logging
          uid: 1c4aeb4c-afb2-4714-b3b0-d1d756f53bdc
    spec:
      clusterIP: None
      clusterIPs:
        - None
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: https
          port: 9200
          protocol: TCP
          targetPort: 9200
      publishNotReadyAddresses: true
      selector:
        common.k8s.elastic.co/type: elasticsearch
        elasticsearch.k8s.elastic.co/cluster-name: logging
        elasticsearch.k8s.elastic.co/statefulset-name: logging-es-default
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: observability:/Service:observability/logging-es-http
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"observability:/Service:observability/logging-es-http"},"creationTimestamp":"2026-02-13T19:05:28Z","labels":{"common.k8s.elastic.co/type":"elasticsearch","elasticsearch.k8s.elastic.co/cluster-name":"logging"},"name":"logging-es-http","namespace":"observability","ownerReferences":[{"apiVersion":"elasticsearch.k8s.elastic.co/v1","blockOwnerDeletion":true,"controller":true,"kind":"Elasticsearch","name":"logging","uid":"1c4aeb4c-afb2-4714-b3b0-d1d756f53bdc"}],"resourceVersion":"4224737","uid":"99787d10-6abe-44c8-96f1-50f9dff516e5"},"spec":{"clusterIP":"10.110.170.201","clusterIPs":["10.110.170.201"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"https","port":9200,"protocol":"TCP","targetPort":9200}],"selector":{"common.k8s.elastic.co/type":"elasticsearch","elasticsearch.k8s.elastic.co/cluster-name":"logging"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
      labels:
        common.k8s.elastic.co/type: elasticsearch
        elasticsearch.k8s.elastic.co/cluster-name: logging
      name: logging-es-http
      namespace: observability
      ownerReferences:
        - apiVersion: elasticsearch.k8s.elastic.co/v1
          blockOwnerDeletion: true
          controller: true
          kind: Elasticsearch
          name: logging
          uid: 1c4aeb4c-afb2-4714-b3b0-d1d756f53bdc
    spec:
      clusterIP: 10.110.170.201
      clusterIPs:
        - 10.110.170.201
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: https
          port: 9200
          protocol: TCP
          targetPort: 9200
      selector:
        common.k8s.elastic.co/type: elasticsearch
        elasticsearch.k8s.elastic.co/cluster-name: logging
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: observability:/Service:observability/logging-es-internal-http
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"observability:/Service:observability/logging-es-internal-http"},"creationTimestamp":"2026-02-13T19:05:28Z","labels":{"common.k8s.elastic.co/type":"elasticsearch","elasticsearch.k8s.elastic.co/cluster-name":"logging"},"name":"logging-es-internal-http","namespace":"observability","ownerReferences":[{"apiVersion":"elasticsearch.k8s.elastic.co/v1","blockOwnerDeletion":true,"controller":true,"kind":"Elasticsearch","name":"logging","uid":"1c4aeb4c-afb2-4714-b3b0-d1d756f53bdc"}],"resourceVersion":"4224740","uid":"271b40c5-c7b4-4477-a8bb-17a5b9cff8cf"},"spec":{"clusterIP":"10.98.47.204","clusterIPs":["10.98.47.204"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"https","port":9200,"protocol":"TCP","targetPort":9200}],"selector":{"common.k8s.elastic.co/type":"elasticsearch","elasticsearch.k8s.elastic.co/cluster-name":"logging"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
      labels:
        common.k8s.elastic.co/type: elasticsearch
        elasticsearch.k8s.elastic.co/cluster-name: logging
      name: logging-es-internal-http
      namespace: observability
      ownerReferences:
        - apiVersion: elasticsearch.k8s.elastic.co/v1
          blockOwnerDeletion: true
          controller: true
          kind: Elasticsearch
          name: logging
          uid: 1c4aeb4c-afb2-4714-b3b0-d1d756f53bdc
    spec:
      clusterIP: 10.98.47.204
      clusterIPs:
        - 10.98.47.204
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: https
          port: 9200
          protocol: TCP
          targetPort: 9200
      selector:
        common.k8s.elastic.co/type: elasticsearch
        elasticsearch.k8s.elastic.co/cluster-name: logging
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: observability:/Service:observability/logging-es-nodeport
        field.cattle.io/publicEndpoints: '[{"port":31200,"protocol":"TCP","serviceName":"observability:logging-es-nodeport","allNodes":true}]'
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"observability:/Service:observability/logging-es-nodeport","field.cattle.io/publicEndpoints":"[{\"port\":31200,\"protocol\":\"TCP\",\"serviceName\":\"observability:logging-es-nodeport\",\"allNodes\":true}]"},"creationTimestamp":"2026-02-13T19:36:31Z","name":"logging-es-nodeport","namespace":"observability","resourceVersion":"4221174","uid":"83b82018-db76-4ec2-9982-f72af4878fe1"},"spec":{"clusterIP":"10.100.255.188","clusterIPs":["10.100.255.188"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"https","nodePort":31200,"port":9200,"protocol":"TCP","targetPort":9200}],"selector":{"common.k8s.elastic.co/type":"elasticsearch","elasticsearch.k8s.elastic.co/cluster-name":"logging","elasticsearch.k8s.elastic.co/statefulset-name":"logging-es-default"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
      name: logging-es-nodeport
      namespace: observability
    spec:
      clusterIP: 10.100.255.188
      clusterIPs:
        - 10.100.255.188
      externalTrafficPolicy: Cluster
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: https
          nodePort: 31200
          port: 9200
          protocol: TCP
          targetPort: 9200
      selector:
        common.k8s.elastic.co/type: elasticsearch
        elasticsearch.k8s.elastic.co/cluster-name: logging
        elasticsearch.k8s.elastic.co/statefulset-name: logging-es-default
      sessionAffinity: None
      type: NodePort
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: observability:/Service:observability/logging-es-nodeport-temp
        field.cattle.io/publicEndpoints: '[{"port":32200,"protocol":"TCP","serviceName":"observability:logging-es-nodeport-temp","allNodes":true},{"port":32300,"protocol":"TCP","serviceName":"observability:logging-es-nodeport-temp","allNodes":true}]'
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"observability:/Service:observability/logging-es-nodeport-temp","field.cattle.io/publicEndpoints":"[{\"port\":32200,\"protocol\":\"TCP\",\"serviceName\":\"observability:logging-es-nodeport-temp\",\"allNodes\":true},{\"port\":32300,\"protocol\":\"TCP\",\"serviceName\":\"observability:logging-es-nodeport-temp\",\"allNodes\":true}]"},"creationTimestamp":"2026-02-20T22:54:50Z","name":"logging-es-nodeport-temp","namespace":"observability","resourceVersion":"4221176","uid":"31d6a228-29f9-43a3-aeea-4dcc0271cdd3"},"spec":{"clusterIP":"10.101.150.143","clusterIPs":["10.101.150.143"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"http","nodePort":32200,"port":9200,"protocol":"TCP","targetPort":9200},{"name":"transport","nodePort":32300,"port":9300,"protocol":"TCP","targetPort":9300}],"selector":{"common.k8s.elastic.co/type":"elasticsearch","elasticsearch.k8s.elastic.co/cluster-name":"logging","elasticsearch.k8s.elastic.co/statefulset-name":"logging-es-default"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
      name: logging-es-nodeport-temp
      namespace: observability
    spec:
      clusterIP: 10.101.150.143
      clusterIPs:
        - 10.101.150.143
      externalTrafficPolicy: Cluster
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http
          nodePort: 32200
          port: 9200
          protocol: TCP
          targetPort: 9200
        - name: transport
          nodePort: 32300
          port: 9300
          protocol: TCP
          targetPort: 9300
      selector:
        common.k8s.elastic.co/type: elasticsearch
        elasticsearch.k8s.elastic.co/cluster-name: logging
        elasticsearch.k8s.elastic.co/statefulset-name: logging-es-default
      sessionAffinity: None
      type: NodePort
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: observability:/Service:observability/logging-es-transport
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"observability:/Service:observability/logging-es-transport"},"creationTimestamp":"2026-02-13T19:05:28Z","labels":{"common.k8s.elastic.co/type":"elasticsearch","elasticsearch.k8s.elastic.co/cluster-name":"logging"},"name":"logging-es-transport","namespace":"observability","ownerReferences":[{"apiVersion":"elasticsearch.k8s.elastic.co/v1","blockOwnerDeletion":true,"controller":true,"kind":"Elasticsearch","name":"logging","uid":"1c4aeb4c-afb2-4714-b3b0-d1d756f53bdc"}],"resourceVersion":"2112767","uid":"df55b5ee-3eb9-4952-afcf-8ad391607d81"},"spec":{"clusterIP":"None","clusterIPs":["None"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"tls-transport","port":9300,"protocol":"TCP","targetPort":9300}],"publishNotReadyAddresses":true,"selector":{"common.k8s.elastic.co/type":"elasticsearch","elasticsearch.k8s.elastic.co/cluster-name":"logging"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
      labels:
        common.k8s.elastic.co/type: elasticsearch
        elasticsearch.k8s.elastic.co/cluster-name: logging
      name: logging-es-transport
      namespace: observability
      ownerReferences:
        - apiVersion: elasticsearch.k8s.elastic.co/v1
          blockOwnerDeletion: true
          controller: true
          kind: Elasticsearch
          name: logging
          uid: 1c4aeb4c-afb2-4714-b3b0-d1d756f53bdc
    spec:
      clusterIP: None
      clusterIPs:
        - None
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: tls-transport
          port: 9300
          protocol: TCP
          targetPort: 9300
      publishNotReadyAddresses: true
      selector:
        common.k8s.elastic.co/type: elasticsearch
        elasticsearch.k8s.elastic.co/cluster-name: logging
      sessionAffinity: None
      type: ClusterIP
kind: List
metadata:
  resourceVersion: ""
