apiVersion: v1
data:
  extraconfig-from-values.hcl: |-
    ui = true

    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
      cluster_address = "[::]:8201"
      # Enable unauthenticated metrics access (necessary for Prometheus Operator)
      #telemetry {
      #  unauthenticated_metrics_access = "true"
      #}
    }

    storage "raft" {
      path = "/vault/data"
    }

    service_registration "kubernetes" {}

    disable_mlock = true
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: vault
    meta.helm.sh/release-namespace: vault
  creationTimestamp: "2026-02-15T18:05:03Z"
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.32.0
  name: vault-config
  namespace: vault
  resourceVersion: "2768063"
  uid: 5c44bbcf-4d04-41c9-ae90-b93a1d056c30
