apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: vault:/Service:vault/vault-standby
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"vault:/Service:vault/vault-standby","meta.helm.sh/release-name":"vault","meta.helm.sh/release-namespace":"vault"},"creationTimestamp":"2026-02-15T18:05:03Z","labels":{"app.kubernetes.io/instance":"vault","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"vault","helm.sh/chart":"vault-0.32.0"},"name":"vault-standby","namespace":"vault","resourceVersion":"2768094","uid":"f71ba68d-a480-4d3b-9d2d-b8ab95de0b1d"},"spec":{"clusterIP":"10.111.47.101","clusterIPs":["10.111.47.101"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"http","port":8200,"protocol":"TCP","targetPort":8200},{"name":"https-internal","port":8201,"protocol":"TCP","targetPort":8201}],"publishNotReadyAddresses":true,"selector":{"app.kubernetes.io/instance":"vault","app.kubernetes.io/name":"vault","component":"server","vault-active":"false"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
    meta.helm.sh/release-name: vault
    meta.helm.sh/release-namespace: vault
  creationTimestamp: "2026-02-15T18:05:03Z"
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.32.0
  name: vault-standby
  namespace: vault
  resourceVersion: "6185623"
  uid: f71ba68d-a480-4d3b-9d2d-b8ab95de0b1d
spec:
  clusterIP: 10.111.47.101
  clusterIPs:
    - 10.111.47.101
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8200
      protocol: TCP
      targetPort: 8200
    - name: https-internal
      port: 8201
      protocol: TCP
      targetPort: 8201
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    component: server
    vault-active: "false"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
