apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: vault:/Service:vault/guestbook-ui
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"vault:/Service:vault/guestbook-ui"},"creationTimestamp":"2026-02-26T04:21:16Z","name":"guestbook-ui","namespace":"vault","resourceVersion":"5841708","uid":"9e77db3d-2eae-4fdf-9594-ec9b2d9c173e"},"spec":{"clusterIP":"10.103.63.151","clusterIPs":["10.103.63.151"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"guestbook-ui"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2026-02-26T04:21:16Z"
  name: guestbook-ui
  namespace: vault
  resourceVersion: "6187562"
  uid: 9e77db3d-2eae-4fdf-9594-ec9b2d9c173e
spec:
  clusterIP: 10.103.63.151
  clusterIPs:
    - 10.103.63.151
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: guestbook-ui
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
