apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: vault:/Service:vault/vault-agent-injector-svc
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"vault:/Service:vault/vault-agent-injector-svc","meta.helm.sh/release-name":"vault","meta.helm.sh/release-namespace":"vault"},"creationTimestamp":"2026-02-15T18:05:03Z","labels":{"app.kubernetes.io/instance":"vault","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"vault-agent-injector"},"name":"vault-agent-injector-svc","namespace":"vault","resourceVersion":"2768081","uid":"b7cb34ca-7b46-4eb0-8fe1-7fa19706607e"},"spec":{"clusterIP":"10.109.95.174","clusterIPs":["10.109.95.174"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"https","port":443,"protocol":"TCP","targetPort":8080}],"selector":{"app.kubernetes.io/instance":"vault","app.kubernetes.io/name":"vault-agent-injector","component":"webhook"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
    meta.helm.sh/release-name: vault
    meta.helm.sh/release-namespace: vault
  creationTimestamp: "2026-02-15T18:05:03Z"
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault-agent-injector
  name: vault-agent-injector-svc
  namespace: vault
  resourceVersion: "6185628"
  uid: b7cb34ca-7b46-4eb0-8fe1-7fa19706607e
spec:
  clusterIP: 10.109.95.174
  clusterIPs:
    - 10.109.95.174
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault-agent-injector
    component: webhook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
