apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: vault:/Service:vault/vault
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"vault:/Service:vault/vault","meta.helm.sh/release-name":"vault","meta.helm.sh/release-namespace":"vault"},"creationTimestamp":"2026-02-15T18:05:03Z","labels":{"app.kubernetes.io/instance":"vault","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"vault","helm.sh/chart":"vault-0.32.0"},"name":"vault","namespace":"vault","resourceVersion":"2768076","uid":"82acb0bb-1060-4e6e-85a4-d8d565fba934"},"spec":{"clusterIP":"10.104.203.24","clusterIPs":["10.104.203.24"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"http","port":8200,"protocol":"TCP","targetPort":8200},{"name":"https-internal","port":8201,"protocol":"TCP","targetPort":8201}],"publishNotReadyAddresses":true,"selector":{"app.kubernetes.io/instance":"vault","app.kubernetes.io/name":"vault","component":"server"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
    meta.helm.sh/release-name: vault
    meta.helm.sh/release-namespace: vault
  creationTimestamp: "2026-02-15T18:05:03Z"
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.32.0
  name: vault
  namespace: vault
  resourceVersion: "6185625"
  uid: 82acb0bb-1060-4e6e-85a4-d8d565fba934
spec:
  clusterIP: 10.104.203.24
  clusterIPs:
    - 10.104.203.24
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8200
      protocol: TCP
      targetPort: 8200
    - name: https-internal
      port: 8201
      protocol: TCP
      targetPort: 8201
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    component: server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
