apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: echo:/Service:echo/echo
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"echo:/Service:echo/echo"},"creationTimestamp":"2026-02-11T10:34:26Z","name":"echo","namespace":"echo","resourceVersion":"1565169","uid":"5fdb3edd-4a21-496d-b8fe-a64566ef10f3"},"spec":{"clusterIP":"10.109.86.105","clusterIPs":["10.109.86.105"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"echo"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
      name: echo
      namespace: echo
    spec:
      clusterIP: 10.109.86.105
      clusterIPs:
        - 10.109.86.105
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - port: 80
          protocol: TCP
          targetPort: 80
      selector:
        app: echo
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: echo:/Service:echo/httpbin
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"echo:/Service:echo/httpbin"},"creationTimestamp":"2026-02-09T12:10:06Z","name":"httpbin","namespace":"echo","resourceVersion":"1346798","uid":"601ed99b-e2b8-45bf-8e89-0c95f18d15b6"},"spec":{"clusterIP":"10.96.91.175","clusterIPs":["10.96.91.175"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"httpbin"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
      name: httpbin
      namespace: echo
    spec:
      clusterIP: 10.96.91.175
      clusterIPs:
        - 10.96.91.175
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 80
      selector:
        app: httpbin
      sessionAffinity: None
      type: ClusterIP
kind: List
metadata:
  resourceVersion: ""
