apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-02-14T09:15:44Z"
    name: default
    namespace: shipper
    resourceVersion: "2312697"
    uid: 0baaf1db-0172-46d5-9d1d-e8495a3450a1
kind: List
metadata:
  resourceVersion: ""
