apiVersion: v1
items:
- apiVersion: v1
  data:
    ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVJ5Z0F3SUJBZ0lSQUpKOERPZU41c3orbDZ3eWs2RkhwcEl3Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FYm1sc01UQWdGdzB5TmpBeU1Ea3hNalV4TlRsYUdBOHlNVEkyTURFeE5qRXlOVEUxT1ZvdwpEekVOTUFzR0ExVUVDaE1FYm1sc01UQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJJNGVSSEh6ClUvclV3di8wb1pLZE15Tkd6eEQybTVzeHJteFhhNTJvU05KVzlpWlhLZWoyN0JrMXMrRFNLYjI5YS9WOGswdUYKMlJPditPQnJWSXl4Mlk2alZ6QlZNQTRHQTFVZER3RUIvd1FFQXdJQ0JEQVRCZ05WSFNVRUREQUtCZ2dyQmdFRgpCUWNEQVRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTQlZPVHYxYm13WU9zMEtvWWg3djIvCkd3K05SekFLQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBbWNEdGwrMHJxdG1oMUFjMWhDTGZuYjlxL21DNnYrYkwKcHZGYVdwTHFGRjBDSVFDUGJkUUFKTktpSXZUamJBMUE2R3ZpZmp5V1EvcHRuWGwvNW1BY1JuK011Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ1ekNDQVdHZ0F3SUJBZ0lSQVA5S1NpeExIWjhPdWlqdFNuR1RqZTR3Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FYm1sc01UQWdGdzB5TmpBeU1Ea3hNalV4TlRsYUdBOHlNVEkyTURFeE5qRXlOVEUxT1ZvdwpEekVOTUFzR0ExVUVDaE1FYm1sc01qQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJBUnhleXF3Clo4V3dSYWs2TWFnUXBJWldscVF0VG1YRzFvL1JpYTR1NVk5QUZHY2FDRW1zZ1NtQjkrQ2ZsYzlnci9Cck1IeFAKU2xyVVp1RGZ1ZG9UbjVlamdac3dnWmd3RGdZRFZSMFBBUUgvQkFRREFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzRwpBUVVGQndNQk1Bd0dBMVVkRXdFQi93UUNNQUF3WXdZRFZSMFJCRnd3V29JaWFXNW5jbVZ6Y3kxdVoybHVlQzFqCmIyNTBjbTlzYkdWeUxXRmtiV2x6YzJsdmJvSTBhVzVuY21WemN5MXVaMmx1ZUMxamIyNTBjbTlzYkdWeUxXRmsKYldsemMybHZiaTVwYm1keVpYTnpMVzVuYVc1NExuTjJZekFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUJDc0xUaApFOG5vbnpBZTFPblp0NlFKOHQzMW52clE0dTFRamIrZzZkUFBCQUloQU1kSUVvaXUvQ2c3WXg5VGVqeSs5UlQ4Ckt5ekc1YWQ4OHFXSUxlWU5iYTV6Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU5XVzVPbEgvUm4zUUl2TkVzM1FnSFU3S1IyZU9sZ3JUTWk4VkNVNGttVm1vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFQkhGN0tyQm54YkJGcVRveHFCQ2tobGFXcEMxT1pjYldqOUdKcmk3bGowQVVaeG9JU2F5QgpLWUgzNEorVnoyQ3Y4R3N3ZkU5S1d0Um00Tis1MmhPZmx3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  kind: Secret
  metadata:
    annotations:
      field.cattle.io/projectId: c-cbbbx:p-5h9q9
    creationTimestamp: "2026-02-09T12:56:59Z"
    name: ingress-nginx-admission
    namespace: ingress-nginx
    resourceVersion: "4181006"
    uid: 0f8186ac-6fbd-4033-a299-593f3e3d74af
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
