apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: ingress-nginx:/Service:ingress-nginx/guestbook-ui
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"ingress-nginx:/Service:ingress-nginx/guestbook-ui"},"creationTimestamp":"2026-02-26T04:21:16Z","name":"guestbook-ui","namespace":"ingress-nginx","resourceVersion":"5841714","uid":"970d65e5-7ef6-4bdb-85d4-e7a6dbde3bcc"},"spec":{"clusterIP":"10.111.25.26","clusterIPs":["10.111.25.26"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"guestbook-ui"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2026-02-26T04:21:16Z"
  name: guestbook-ui
  namespace: ingress-nginx
  resourceVersion: "6187564"
  uid: 970d65e5-7ef6-4bdb-85d4-e7a6dbde3bcc
spec:
  clusterIP: 10.111.25.26
  clusterIPs:
    - 10.111.25.26
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: guestbook-ui
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
