apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-13T23:45:46Z"
    name: default
    namespace: network-tester
    resourceVersion: "10144577"
    uid: b36b814b-d6d3-4f10-ad11-3877cf0032d5
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: network-tester:/ServiceAccount:network-tester/network-tester-sa
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"network-tester:/ServiceAccount:network-tester/network-tester-sa"},"name":"network-tester-sa","namespace":"network-tester"}}
    creationTimestamp: "2026-03-13T23:45:46Z"
    name: network-tester-sa
    namespace: network-tester
    resourceVersion: "10152174"
    uid: cf2ccdd2-b30f-4fdb-a928-7267935d1ce5
kind: List
metadata:
  resourceVersion: ""
