apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-03-14T00:45:46Z"
    name: default
    namespace: abu7midan-website
    resourceVersion: "10154649"
    uid: 4c5e9cca-eee3-4d19-af81-7bdddaa3a1e5
kind: List
metadata:
  resourceVersion: ""
