apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBTCCAe2gAwIBAgIIDqtKmA2hLZYwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczAeFw0yNjAxMzAxMDE3MTVaFw0zNjAxMjgxMDIyMTVaMBUx
    EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDAa+5Kr9G5n1h+BeHS4t41RkUCtR0s+zc3odysP/vj7hmrCGcW8tx+6PLD
    AqcGki9/uEQ0Te7kL55lI/rPbT3e1MsoduokwS3tMj5hHZoKlbE+TflcFsdX2KSG
    L45UwL4RifrdAGGK+dGpdL+gN1Cvh0ykNibx73Wm+ObfAYH2vkr2gtttnW9j6w+y
    AVVCpLzFBQtdlLluGLQZe7gW20kmU7zJmeZkixZLerW7QNXH8uSt2WAfBSCnOM2e
    WiYgz6qUIZPrBHQ5Zkl0xLFTLulKbPJRvxXdwSQbsObpq/G/mXvWiVX+64ZwNLpK
    aUQHnUGHPm5m3livNpneSGHS7xQXAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSg9wtwOXh5UxEu+26CNSwkbpS4LTAV
    BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQB7mdzAzYgL
    LbaQANU6H2H15cOeN+Jz4lqnUqo5Mqla9I2xd3YcczugEnVApaHz8vmLCEIq6fI0
    5rpcml1b/wmP3IbC57nnhcqfCKm+3G48uDxK7JCRJrfI0VDg0ZkImZEd5J5EUNIi
    nnppYBWKLbwtLi2aooGPtBExruN1o6rKit7g0kFPwoYGGOEBaF1sKGBy98w5EEs/
    L9fVWXP2V/v0Gu+lTfsasZZ/jlmjM2Tm7671T95+xnGDQDoM8CmgUP3E0QV9/ug0
    /L+iIMOLD5DgN1fp7T5iNoWPEd6hcNuZxjHGHFMp0lA7Zn4TraYQih69lmQjtlx1
    6uooniAO0xc2
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: strimzi:/ConfigMap:strimzi/kube-root-ca.crt
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ca.crt":"-----BEGIN CERTIFICATE-----\nMIIDBTCCAe2gAwIBAgIIDqtKmA2hLZYwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE\nAxMKa3ViZXJuZXRlczAeFw0yNjAxMzAxMDE3MTVaFw0zNjAxMjgxMDIyMTVaMBUx\nEzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK\nAoIBAQDAa+5Kr9G5n1h+BeHS4t41RkUCtR0s+zc3odysP/vj7hmrCGcW8tx+6PLD\nAqcGki9/uEQ0Te7kL55lI/rPbT3e1MsoduokwS3tMj5hHZoKlbE+TflcFsdX2KSG\nL45UwL4RifrdAGGK+dGpdL+gN1Cvh0ykNibx73Wm+ObfAYH2vkr2gtttnW9j6w+y\nAVVCpLzFBQtdlLluGLQZe7gW20kmU7zJmeZkixZLerW7QNXH8uSt2WAfBSCnOM2e\nWiYgz6qUIZPrBHQ5Zkl0xLFTLulKbPJRvxXdwSQbsObpq/G/mXvWiVX+64ZwNLpK\naUQHnUGHPm5m3livNpneSGHS7xQXAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP\nBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSg9wtwOXh5UxEu+26CNSwkbpS4LTAV\nBgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQB7mdzAzYgL\nLbaQANU6H2H15cOeN+Jz4lqnUqo5Mqla9I2xd3YcczugEnVApaHz8vmLCEIq6fI0\n5rpcml1b/wmP3IbC57nnhcqfCKm+3G48uDxK7JCRJrfI0VDg0ZkImZEd5J5EUNIi\nnnppYBWKLbwtLi2aooGPtBExruN1o6rKit7g0kFPwoYGGOEBaF1sKGBy98w5EEs/\nL9fVWXP2V/v0Gu+lTfsasZZ/jlmjM2Tm7671T95+xnGDQDoM8CmgUP3E0QV9/ug0\n/L+iIMOLD5DgN1fp7T5iNoWPEd6hcNuZxjHGHFMp0lA7Zn4TraYQih69lmQjtlx1\n6uooniAO0xc2\n-----END CERTIFICATE-----\n"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"strimzi:/ConfigMap:strimzi/kube-root-ca.crt","kubernetes.io/description":"Contains a CA bundle that can be used to verify the kube-apiserver when using internal endpoints such as the internal service IP or kubernetes.default.svc. No other usage is guaranteed across distributions of Kubernetes clusters."},"creationTimestamp":"2026-02-12T13:59:18Z","name":"kube-root-ca.crt","namespace":"strimzi","resourceVersion":"1803197","uid":"77f53001-3a5c-450c-bcad-817210558de3"}}
    kubernetes.io/description: Contains a CA bundle that can be used to verify the kube-apiserver when using internal endpoints such as the internal service IP or kubernetes.default.svc. No other usage is guaranteed across distributions of Kubernetes clusters.
  creationTimestamp: "2026-02-12T13:59:18Z"
  name: kube-root-ca.crt
  namespace: strimzi
  resourceVersion: "6186592"
  uid: 77f53001-3a5c-450c-bcad-817210558de3
