apiVersion: v1
data:
  log4j2.properties: |
    name = COConfig
    monitorInterval = 30

    appender.console.type = Console
    appender.console.name = STDOUT
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

    rootLogger.level = ${env:STRIMZI_LOG_LEVEL:-INFO}
    rootLogger.appenderRefs = stdout
    rootLogger.appenderRef.console.ref = STDOUT

    # Kafka AdminClient logging is a bit noisy at INFO level
    logger.kafka.name = org.apache.kafka
    logger.kafka.level = WARN

    # Keeps separate level for Netty logging -> to not be changed by the root logger
    logger.netty.name = io.netty
    logger.netty.level = INFO
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: strimzi:/ConfigMap:strimzi/strimzi-cluster-operator
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"log4j2.properties":"name = COConfig\nmonitorInterval = 30\n\nappender.console.type = Console\nappender.console.name = STDOUT\nappender.console.layout.type = PatternLayout\nappender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n\n\nrootLogger.level = ${env:STRIMZI_LOG_LEVEL:-INFO}\nrootLogger.appenderRefs = stdout\nrootLogger.appenderRef.console.ref = STDOUT\n\n# Kafka AdminClient logging is a bit noisy at INFO level\nlogger.kafka.name = org.apache.kafka\nlogger.kafka.level = WARN\n\n# Keeps separate level for Netty logging -\u003e to not be changed by the root logger\nlogger.netty.name = io.netty\nlogger.netty.level = INFO\n"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"strimzi:/ConfigMap:strimzi/strimzi-cluster-operator"},"creationTimestamp":"2026-02-12T13:59:22Z","labels":{"app":"strimzi"},"name":"strimzi-cluster-operator","namespace":"strimzi","resourceVersion":"1803221","uid":"3e52cb69-192a-4ae5-b512-0cbaa2729323"}}
  creationTimestamp: "2026-02-12T13:59:22Z"
  labels:
    app: strimzi
  name: strimzi-cluster-operator
  namespace: strimzi
  resourceVersion: "6186591"
  uid: 3e52cb69-192a-4ae5-b512-0cbaa2729323
