apiVersion: v1
data:
  password: a29uZ3Bhc3M=
  postgres-password: a29uZ3Bhc3M=
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: kong:/Secret:kong/kong-postgresql
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"password":"a29uZ3Bhc3M=","postgres-password":"a29uZ3Bhc3M="},"kind":"Secret","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"kong:/Secret:kong/kong-postgresql"},"creationTimestamp":"2026-03-03T03:24:06Z","name":"kong-postgresql","namespace":"kong","resourceVersion":"7189592","uid":"232646a7-6600-4d2e-9d20-6b1e544ea7ff"},"type":"Opaque"}
  creationTimestamp: "2026-03-14T13:23:58Z"
  name: kong-postgresql
  namespace: kong
  resourceVersion: "10273042"
  uid: 5b463644-b21f-4e87-aa88-0ad4def109f7
type: Opaque
