apiVersion: v1
data:
  database: a29uZ2E=
  password: a29uZ2E=
  username: a29uZ2E=
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: kong:/Secret:kong/konga-mongodb
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"database":"a29uZ2E=","password":"a29uZ2E=","username":"a29uZ2E="},"kind":"Secret","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"kong:/Secret:kong/konga-mongodb"},"creationTimestamp":"2026-03-03T03:32:58Z","name":"konga-mongodb","namespace":"kong","resourceVersion":"7191460","uid":"c8ee7261-5959-40d5-802b-da283689426c"},"type":"Opaque"}
  creationTimestamp: "2026-03-14T13:23:58Z"
  name: konga-mongodb
  namespace: kong
  resourceVersion: "10273043"
  uid: a853257d-ae2b-4472-bc6b-5ab95615518f
type: Opaque
