apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/deployment.yaml
- base/services.yaml
- base/secrets.yaml
- base/configmaps.yaml
- base/ingressclass.yaml
- base/postgresql-deployment.yaml
- base/mongodb-deployment.yaml
- base/konga-deployment.yaml
- base/konga-ingress-current.yaml

namespace: kong
