apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/configmaps.yaml
- base/deployment.yaml
- base/ingressclass.yaml
- base/konga-ingress-current.yaml
- base/namespace.yaml
- base/secrets.yaml
- base/services.yaml

namespace: kong
- base/serviceaccount.yaml
- base/migrations-job.yaml
