apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: shipper:/Service:shipper/spce-shipper
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"shipper:/Service:shipper/spce-shipper"},"creationTimestamp":"2026-02-14T09:15:44Z","name":"spce-shipper","namespace":"shipper","resourceVersion":"2312702","uid":"0f8cb62f-3e5a-4151-8ec4-036891d22592"},"spec":{"clusterIP":"10.101.163.13","clusterIPs":["10.101.163.13"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"spce-shipper"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
    creationTimestamp: "2026-02-14T09:15:44Z"
    name: spce-shipper
    namespace: shipper
    resourceVersion: "6186574"
    uid: 0f8cb62f-3e5a-4151-8ec4-036891d22592
  spec:
    clusterIP: 10.101.163.13
    clusterIPs:
    - 10.101.163.13
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: spce-shipper
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: shipper:apps/Deployment:shipper/spce-shipper
      deployment.kubernetes.io/revision: "3"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"shipper:apps/Deployment:shipper/spce-shipper","deployment.kubernetes.io/revision":"3"},"creationTimestamp":"2026-02-14T09:15:44Z","generation":4,"name":"spce-shipper","namespace":"shipper","resourceVersion":"4242592","uid":"ca12e550-3967-4470-b5fd-7b18346f3962"},"spec":{"progressDeadlineSeconds":600,"replicas":0,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"spce-shipper"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"cattle.io/timestamp":"2026-02-14T09:18:28Z"},"labels":{"app":"spce-shipper"}},"spec":{"containers":[{"env":[{"name":"ASPNETCORE_URLS","value":"http://+:8080"},{"name":"Kafka__BootstrapServers","value":"my-kafka-kafka-bootstrap.kafka.svc:9092"},{"name":"Kafka__ShipmentRequestsTopic","value":"shipment-requests"},{"name":"Kafka__ShipmentsTopic","value":"shipments"},{"name":"Kafka__ConsumerGroup","value":"spce-shipper"}],"image":"abu7midan/spce-shipper:1.0","imagePullPolicy":"IfNotPresent","name":"spce-shipper","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"conditions":[{"lastTransitionTime":"2026-02-14T09:15:44Z","lastUpdateTime":"2026-02-14T09:19:36Z","message":"ReplicaSet \"spce-shipper-655c96b9cf\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2026-02-20T21:03:11Z","lastUpdateTime":"2026-02-20T21:03:11Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":4}}
    creationTimestamp: "2026-02-14T09:15:44Z"
    generation: 5
    name: spce-shipper
    namespace: shipper
    resourceVersion: "6186589"
    uid: ca12e550-3967-4470-b5fd-7b18346f3962
  spec:
    progressDeadlineSeconds: 600
    replicas: 0
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: spce-shipper
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          cattle.io/timestamp: "2026-02-14T09:18:28Z"
        labels:
          app: spce-shipper
      spec:
        containers:
        - env:
          - name: ASPNETCORE_URLS
            value: http://+:8080
          - name: Kafka__BootstrapServers
            value: my-kafka-kafka-bootstrap.kafka.svc:9092
          - name: Kafka__ShipmentRequestsTopic
            value: shipment-requests
          - name: Kafka__ShipmentsTopic
            value: shipments
          - name: Kafka__ConsumerGroup
            value: spce-shipper
          image: abu7midan/spce-shipper:1.0
          imagePullPolicy: IfNotPresent
          name: spce-shipper
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2026-02-14T09:15:44Z"
      lastUpdateTime: "2026-02-14T09:19:36Z"
      message: ReplicaSet "spce-shipper-655c96b9cf" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-02-20T21:03:11Z"
      lastUpdateTime: "2026-02-20T21:03:11Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 5
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: shipper:apps/Deployment:shipper/spce-shipper
      deployment.kubernetes.io/desired-replicas: "0"
      deployment.kubernetes.io/max-replicas: "0"
      deployment.kubernetes.io/revision: "3"
    creationTimestamp: "2026-02-14T09:19:28Z"
    generation: 3
    labels:
      app: spce-shipper
      pod-template-hash: 655c96b9cf
    name: spce-shipper-655c96b9cf
    namespace: shipper
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: spce-shipper
      uid: ca12e550-3967-4470-b5fd-7b18346f3962
    resourceVersion: "6186588"
    uid: a8f5675d-c62f-4ff6-8419-b964cd43c35b
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: spce-shipper
        pod-template-hash: 655c96b9cf
    template:
      metadata:
        annotations:
          cattle.io/timestamp: "2026-02-14T09:18:28Z"
        labels:
          app: spce-shipper
          pod-template-hash: 655c96b9cf
      spec:
        containers:
        - env:
          - name: ASPNETCORE_URLS
            value: http://+:8080
          - name: Kafka__BootstrapServers
            value: my-kafka-kafka-bootstrap.kafka.svc:9092
          - name: Kafka__ShipmentRequestsTopic
            value: shipment-requests
          - name: Kafka__ShipmentsTopic
            value: shipments
          - name: Kafka__ConsumerGroup
            value: spce-shipper
          image: abu7midan/spce-shipper:1.0
          imagePullPolicy: IfNotPresent
          name: spce-shipper
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    observedGeneration: 3
    replicas: 0
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "2"
    creationTimestamp: "2026-02-14T09:18:27Z"
    generation: 2
    labels:
      app: spce-shipper
      pod-template-hash: 6dfbbccbf5
    name: spce-shipper-6dfbbccbf5
    namespace: shipper
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: spce-shipper
      uid: ca12e550-3967-4470-b5fd-7b18346f3962
    resourceVersion: "2313810"
    uid: 153eb6d2-9dd7-4498-a256-e00915e9e6f6
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: spce-shipper
        pod-template-hash: 6dfbbccbf5
    template:
      metadata:
        annotations:
          cattle.io/timestamp: "2026-02-14T09:18:28Z"
        labels:
          app: spce-shipper
          pod-template-hash: 6dfbbccbf5
      spec:
        containers:
        - env:
          - name: ASPNETCORE_URLS
            value: http://+:8080
          - name: Kafka__BootstrapServers
            value: my-kafka-kafka-bootstrap.kafka.svc:9092
          - name: Kafka__ShipmentRequestsTopic
            value: shipment-requests
          - name: Kafka__ShipmentsTopic
            value: shipments
          - name: Kafka__ConsumerGroup
            value: spce-shipper
          image: YOURUSER/spce-shipper:1.0
          imagePullPolicy: IfNotPresent
          name: spce-shipper
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    observedGeneration: 2
    replicas: 0
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2026-02-14T09:15:44Z"
    generation: 2
    labels:
      app: spce-shipper
      pod-template-hash: 75cb584b77
    name: spce-shipper-75cb584b77
    namespace: shipper
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: spce-shipper
      uid: ca12e550-3967-4470-b5fd-7b18346f3962
    resourceVersion: "2313747"
    uid: 0d323de3-d6b0-4a00-b493-8f55e227ed9c
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: spce-shipper
        pod-template-hash: 75cb584b77
    template:
      metadata:
        labels:
          app: spce-shipper
          pod-template-hash: 75cb584b77
      spec:
        containers:
        - env:
          - name: ASPNETCORE_URLS
            value: http://+:8080
          - name: Kafka__BootstrapServers
            value: my-kafka-kafka-bootstrap.kafka.svc:9092
          - name: Kafka__ShipmentRequestsTopic
            value: shipment-requests
          - name: Kafka__ShipmentsTopic
            value: shipments
          - name: Kafka__ConsumerGroup
            value: spce-shipper
          image: YOURUSER/spce-shipper:1.0
          imagePullPolicy: IfNotPresent
          name: spce-shipper
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    observedGeneration: 2
    replicas: 0
kind: List
metadata:
  resourceVersion: ""
