apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-02-12T13:59:18Z"
    name: default
    namespace: strimzi
    resourceVersion: "1803199"
    uid: d47f0da5-3e09-4998-9a7a-2cc247890135
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"strimzi"},"name":"strimzi-cluster-operator","namespace":"strimzi"}}
    creationTimestamp: "2026-02-12T13:59:23Z"
    labels:
      app: strimzi
    name: strimzi-cluster-operator
    namespace: strimzi
    resourceVersion: "1803244"
    uid: d5373e96-61b3-4c0a-bd55-ce2919b9bfb3
kind: List
metadata:
  resourceVersion: ""
