apiVersion: v1
data:
  log4j2.properties: |
    # Do not change this generated file. Logging can be configured in the corresponding Kubernetes resource.
    name=UOConfig
    appender.console.type=Console
    appender.console.name=STDOUT
    appender.console.layout.type=PatternLayout
    appender.console.layout.pattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
    rootLogger.level=INFO
    rootLogger.appenderRefs=stdout
    rootLogger.appenderRef.console.ref=STDOUT
    rootLogger.additivity=false
    logger.jetty.name=org.eclipse.jetty
    logger.jetty.level=INFO
    logger.jetty.additivity=false

    monitorInterval=30
kind: ConfigMap
metadata:
  creationTimestamp: "2026-02-12T14:33:57Z"
  labels:
    app.kubernetes.io/instance: my-kafka
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: entity-user-operator
    app.kubernetes.io/part-of: strimzi-my-kafka
    strimzi.io/cluster: my-kafka
    strimzi.io/component-type: entity-user-operator
    strimzi.io/kind: Kafka
    strimzi.io/name: my-kafka-entity-user-operator
  name: my-kafka-entity-user-operator-config
  namespace: kafka
  ownerReferences:
    - apiVersion: kafka.strimzi.io/v1beta2
      blockOwnerDeletion: true
      controller: false
      kind: Kafka
      name: my-kafka
      uid: 2f4ace1b-eded-4ed3-8750-f4a99bb1cbad
  resourceVersion: "1809559"
  uid: ad04857b-beeb-4c64-b764-57aaf99a8b44
