apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"port":31726,"protocol":"TCP","serviceName":"kafka:my-kafka-brokers-2","allNodes":true}]'
  creationTimestamp: "2026-02-12T14:32:51Z"
  labels:
    app.kubernetes.io/instance: my-kafka
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: strimzi-my-kafka
    strimzi.io/cluster: my-kafka
    strimzi.io/component-type: kafka
    strimzi.io/kind: Kafka
    strimzi.io/name: my-kafka-kafka
    strimzi.io/pool-name: brokers
  name: my-kafka-brokers-2
  namespace: kafka
  ownerReferences:
    - apiVersion: kafka.strimzi.io/v1beta2
      blockOwnerDeletion: true
      controller: false
      kind: KafkaNodePool
      name: brokers
      uid: 88381bb1-0e01-4e9a-a44c-5ffedb62239e
  resourceVersion: "6185691"
  uid: a30d7bdc-c177-43c8-b578-ea13424af0d1
spec:
  clusterIP: 10.107.65.129
  clusterIPs:
    - 10.107.65.129
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp-external
      nodePort: 31726
      port: 9094
      protocol: TCP
      targetPort: tcp-external
  selector:
    strimzi.io/cluster: my-kafka
    strimzi.io/kind: Kafka
    strimzi.io/name: my-kafka-kafka
    strimzi.io/pod-name: my-kafka-brokers-2
    strimzi.io/pool-name: brokers
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
