apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"port":30539,"protocol":"TCP","serviceName":"kafka:my-kafka-brokers-1","allNodes":true}]'
  creationTimestamp: "2026-02-12T14:32:51Z"
  labels:
    app.kubernetes.io/instance: my-kafka
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: strimzi-my-kafka
    strimzi.io/cluster: my-kafka
    strimzi.io/component-type: kafka
    strimzi.io/kind: Kafka
    strimzi.io/name: my-kafka-kafka
    strimzi.io/pool-name: brokers
  name: my-kafka-brokers-1
  namespace: kafka
  ownerReferences:
    - apiVersion: kafka.strimzi.io/v1beta2
      blockOwnerDeletion: true
      controller: false
      kind: KafkaNodePool
      name: brokers
      uid: 88381bb1-0e01-4e9a-a44c-5ffedb62239e
  resourceVersion: "6185689"
  uid: 3976e723-84b3-4dfe-a101-cc402a21a2f9
spec:
  clusterIP: 10.103.33.91
  clusterIPs:
    - 10.103.33.91
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp-external
      nodePort: 30539
      port: 9094
      protocol: TCP
      targetPort: tcp-external
  selector:
    strimzi.io/cluster: my-kafka
    strimzi.io/kind: Kafka
    strimzi.io/name: my-kafka-kafka
    strimzi.io/pod-name: my-kafka-brokers-1
    strimzi.io/pool-name: brokers
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
