apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-02-13T13:06:17Z"
    name: default
    namespace: orders
    resourceVersion: "2042338"
    uid: 230594af-4a96-46cc-9d37-0eaff818ad0c
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-02-15T18:40:46Z"
    name: spce-orders
    namespace: orders
    resourceVersion: "2777104"
    uid: f2b40bba-6a55-4ebd-903a-8616bd3d45ba
kind: List
metadata:
  resourceVersion: ""
