apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: cert-manager:/Service:cert-manager/cert-manager-cainjector
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"cert-manager:/Service:cert-manager/cert-manager-cainjector","meta.helm.sh/release-name":"cert-manager","meta.helm.sh/release-namespace":"cert-manager"},"creationTimestamp":"2026-02-11T15:26:44Z","labels":{"app":"cainjector","app.kubernetes.io/component":"cainjector","app.kubernetes.io/instance":"cert-manager","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"cainjector","app.kubernetes.io/version":"v1.19.3","helm.sh/chart":"cert-manager-v1.19.3"},"name":"cert-manager-cainjector","namespace":"cert-manager","resourceVersion":"1610100","uid":"5b85d205-bc47-4a86-94c6-1894ae5e9e28"},"spec":{"clusterIP":"10.98.235.69","clusterIPs":["10.98.235.69"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"http-metrics","port":9402,"protocol":"TCP","targetPort":9402}],"selector":{"app.kubernetes.io/component":"cainjector","app.kubernetes.io/instance":"cert-manager","app.kubernetes.io/name":"cainjector"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
    meta.helm.sh/release-name: cert-manager
    meta.helm.sh/release-namespace: cert-manager
  creationTimestamp: "2026-02-11T15:26:44Z"
  labels:
    app: cainjector
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/version: v1.19.3
    helm.sh/chart: cert-manager-v1.19.3
  name: cert-manager-cainjector
  namespace: cert-manager
  resourceVersion: "6185602"
  uid: 5b85d205-bc47-4a86-94c6-1894ae5e9e28
spec:
  clusterIP: 10.98.235.69
  clusterIPs:
    - 10.98.235.69
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http-metrics
      port: 9402
      protocol: TCP
      targetPort: 9402
  selector:
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cainjector
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
