apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-02-13T19:38:50Z"
    name: default
    namespace: monitoring
    resourceVersion: "2120974"
    uid: f3ce47f2-ce27-4840-9663-d88b658272e5
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: monitoring
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2026-02-13T19:39:09Z"
    labels:
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 12.3.3
      helm.sh/chart: grafana-11.1.3
    name: monitoring-grafana
    namespace: monitoring
    resourceVersion: "2121128"
    uid: 1d7712ac-1dba-42f7-818b-7a4e4d6597f3
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: monitoring
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2026-02-13T19:39:09Z"
    labels:
      app: kube-prometheus-stack-alertmanager
      app.kubernetes.io/component: alertmanager
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-prometheus-stack-alertmanager
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 81.6.7
      chart: kube-prometheus-stack-81.6.7
      heritage: Helm
      release: monitoring
    name: monitoring-kube-prometheus-alertmanager
    namespace: monitoring
    resourceVersion: "2121124"
    uid: c88fdee5-34a9-4bb5-9144-fedae761c127
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: monitoring
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2026-02-13T19:39:09Z"
    labels:
      app: kube-prometheus-stack-operator
      app.kubernetes.io/component: prometheus-operator
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 81.6.7
      chart: kube-prometheus-stack-81.6.7
      heritage: Helm
      release: monitoring
    name: monitoring-kube-prometheus-operator
    namespace: monitoring
    resourceVersion: "2121125"
    uid: 87d58588-2569-4a91-8229-62589825cafc
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: monitoring
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2026-02-13T19:39:09Z"
    labels:
      app: kube-prometheus-stack-prometheus
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-prometheus-stack-prometheus
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 81.6.7
      chart: kube-prometheus-stack-81.6.7
      heritage: Helm
      release: monitoring
    name: monitoring-kube-prometheus-prometheus
    namespace: monitoring
    resourceVersion: "2121126"
    uid: 3f1a4316-9b08-41e0-9c62-91b8acab312f
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: monitoring
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2026-02-13T19:39:09Z"
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/part-of: kube-state-metrics
      app.kubernetes.io/version: 2.18.0
      helm.sh/chart: kube-state-metrics-7.1.0
      release: monitoring
    name: monitoring-kube-state-metrics
    namespace: monitoring
    resourceVersion: "2121129"
    uid: 56edd26c-b7c8-4fe0-9bf3-9661e927af74
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: monitoring
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2026-02-13T19:39:09Z"
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: prometheus-node-exporter
      app.kubernetes.io/part-of: prometheus-node-exporter
      app.kubernetes.io/version: 1.10.2
      helm.sh/chart: prometheus-node-exporter-4.51.1
      release: monitoring
    name: monitoring-prometheus-node-exporter
    namespace: monitoring
    resourceVersion: "2121127"
    uid: 85155041-8593-4836-934c-545f052de87f
kind: List
metadata:
  resourceVersion: ""
