apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-02-13T19:49:17Z"
    name: default
    namespace: logging
    resourceVersion: "2123920"
    uid: e3325a35-912b-41a4-a199-2bd8e2dca493
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"fluent-bit","namespace":"logging"}}
    creationTimestamp: "2026-02-13T19:50:55Z"
    name: fluent-bit
    namespace: logging
    resourceVersion: "2124309"
    uid: 26fcb19c-89e2-48be-a9de-84d8fd7b8cf3
kind: List
metadata:
  resourceVersion: ""
